import { CMD_3102 } from '@/engine/game/pc/3102/CMD_3102';
import styels from './index.module.scss';

// 特码tab标题及内容
export const tabListFirst = [
  {
    title: '冠军',
    key: '1',
    listKey: 'firstArr',
  },
  {
    title: '亚军',
    key: '2',
    listKey: 'secArr',
  },
  {
    title: '第三名',
    key: '3',
    listKey: 'thirArr',
  },
  {
    title: '第四名',
    key: '4',
    listKey: 'forthArr',
  },
  {
    title: '第五名',
    key: '5',
    listKey: 'fifthArr',
  },
  {
    title: '第六名',
    key: '6',
    listKey: 'sixArr',
  },
  {
    title: '第七名',
    key: '7',
    listKey: 'sevArr',
  },
  {
    title: '第八名',
    key: '8',
    listKey: 'eightArr',
  },
  {
    title: '第九名',
    key: '9',
    listKey: 'nineArr',
  },
  {
    title: '第十名',
    key: '10',
    listKey: 'tenArr',
  },
];

export const tabListSecond = [
  {
    title: '冠亚军和',
    key: '1',
    listKey: 'fsArr',
  },
  {
    title: '冠军',
    key: '2',
    listKey: 'fsArr_1',
  },
  {
    title: '亚军',
    key: '3',
    listKey: 'thrArr',
  },
  {
    title: '第三名',
    key: '4',
    listKey: 'lhhArr',
  },
  {
    title: '第四名',
    key: '5',
    listKey: 'lhhArr',
  },
  {
    title: '第五名',
    key: '6',
    listKey: 'lhhArr',
  },
  {
    title: '第六名',
    key: '7',
    listKey: 'lhhArr',
  },
  {
    title: '第七名',
    key: '8',
    listKey: 'lhhArr',
  },
  {
    title: '第八名',
    key: '9',
    listKey: 'lhhArr',
  },
  {
    title: '第九名',
    key: '10',
    listKey: 'lhhArr',
  },
  {
    title: '第十名',
    key: '11',
    listKey: 'lhhArr',
  },
];


export const betNumberList = [
  {
    title: '数字盘',
    paneKey: '1',
    list: [
      {
        text: '1',
        mutil: 'MT_RANK1_1',
        key: '',
        mainType: 'BTM_RANK_1',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '2',
        mutil: 'MT_RANK1_2',
        key: '',
        mainType: 'BTM_RANK_1',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '3',
        mutil: 'MT_RANK1_3',
        key: '',
        mainType: 'BTM_RANK_1',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '4',
        mutil: 'MT_RANK1_4',
        key: '',
        mainType: 'BTM_RANK_1',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '5',
        mutil: 'MT_RANK1_5',
        key: '',
        mainType: 'BTM_RANK_1',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '6',
        mutil: 'MT_RANK1_6',
        key: '',
        mainType: 'BTM_RANK_1',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '7',
        mutil: 'MT_RANK1_7',
        key: '',
        mainType: 'BTM_RANK_1',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '8',
        mutil: 'MT_RANK1_8',
        key: '',
        mainType: 'BTM_RANK_1',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '9',
        mutil: 'MT_RANK1_9',
        key: '',
        mainType: 'BTM_RANK_1',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '10',
        mutil: 'MT_RANK1_10',
        key: '',
        mainType: 'BTM_RANK_1',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },

      /////////////////亚军
      {
        text: '1',
        mutil: 'MT_RANK2_1',
        key: '',
        mainType: 'BTM_RANK_2',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '2',
        mutil: 'MT_RANK2_2',
        key: '',
        mainType: 'BTM_RANK_2',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '3',
        mutil: 'MT_RANK2_3',
        key: '',
        mainType: 'BTM_RANK_2',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '4',
        mutil: 'MT_RANK2_4',
        key: '',
        mainType: 'BTM_RANK_2',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '5',
        mutil: 'MT_RANK2_5',
        key: '',
        mainType: 'BTM_RANK_2',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '6',
        mutil: 'MT_RANK2_6',
        key: '',
        mainType: 'BTM_RANK_2',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '7',
        mutil: 'MT_RANK2_7',
        key: '',
        mainType: 'BTM_RANK_2',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '8',
        mutil: 'MT_RANK2_8',
        key: '',
        mainType: 'BTM_RANK_2',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '9',
        mutil: 'MT_RANK2_9',
        key: '',
        mainType: 'BTM_RANK_2',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '10',
        mutil: 'MT_RANK2_10',
        key: '',
        mainType: 'BTM_RANK_2',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      /// 第三名
      {
        text: '1',
        mutil: 'MT_RANK3_1',
        key: '',
        mainType: 'BTM_RANK_3',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '2',
        mutil: 'MT_RANK3_2',
        key: '',
        mainType: 'BTM_RANK_3',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '3',
        mutil: 'MT_RANK3_3',
        key: '',
        mainType: 'BTM_RANK_3',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '4',
        mutil: 'MT_RANK3_4',
        key: '',
        mainType: 'BTM_RANK_3',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '5',
        mutil: 'MT_RANK3_5',
        key: '',
        mainType: 'BTM_RANK_3',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '6',
        mutil: 'MT_RANK3_6',
        key: '',
        mainType: 'BTM_RANK_3',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '7',
        mutil: 'MT_RANK3_7',
        key: '',
        mainType: 'BTM_RANK_3',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '8',
        mutil: 'MT_RANK3_8',
        key: '',
        mainType: 'BTM_RANK_3',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '9',
        mutil: 'MT_RANK3_9',
        key: '',
        mainType: 'BTM_RANK_3',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '10',
        mutil: 'MT_RANK3_10',
        key: '',
        mainType: 'BTM_RANK_3',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      ////第四名
      {
        text: '1',
        mutil: 'MT_RANK4_1',
        key: '',
        mainType: 'BTM_RANK_4',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '2',
        mutil: 'MT_RANK4_2',
        key: '',
        mainType: 'BTM_RANK_4',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '3',
        mutil: 'MT_RANK4_3',
        key: '',
        mainType: 'BTM_RANK_4',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '4',
        mutil: 'MT_RANK4_4',
        key: '',
        mainType: 'BTM_RANK_4',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '5',
        mutil: 'MT_RANK4_5',
        key: '',
        mainType: 'BTM_RANK_4',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '6',
        mutil: 'MT_RANK4_6',
        key: '',
        mainType: 'BTM_RANK_4',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '7',
        mutil: 'MT_RANK4_7',
        key: '',
        mainType: 'BTM_RANK_4',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '8',
        mutil: 'MT_RANK4_8',
        key: '',
        mainType: 'BTM_RANK_4',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '9',
        mutil: 'MT_RANK4_9',
        key: '',
        mainType: 'BTM_RANK_4',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '10',
        mutil: 'MT_RANK4_10',
        key: '',
        mainType: 'BTM_RANK_4',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      ///第五名
      {
        text: '1',
        mutil: 'MT_RANK5_1',
        key: '',
        mainType: 'BTM_RANK_5',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '2',
        mutil: 'MT_RANK5_2',
        key: '',
        mainType: 'BTM_RANK_5',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '3',
        mutil: 'MT_RANK5_3',
        key: '',
        mainType: 'BTM_RANK_5',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '4',
        mutil: 'MT_RANK5_4',
        key: '',
        mainType: 'BTM_RANK_5',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '5',
        mutil: 'MT_RANK5_5',
        key: '',
        mainType: 'BTM_RANK_5',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '6',
        mutil: 'MT_RANK5_6',
        key: '',
        mainType: 'BTM_RANK_5',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '7',
        mutil: 'MT_RANK5_7',
        key: '',
        mainType: 'BTM_RANK_5',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '8',
        mutil: 'MT_RANK5_8',
        key: '',
        mainType: 'BTM_RANK_5',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '9',
        mutil: 'MT_RANK5_9',
        key: '',
        mainType: 'BTM_RANK_5',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '10',
        mutil: 'MT_RANK5_10',
        key: '',
        mainType: 'BTM_RANK_5',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      ////第六名
      {
        text: '1',
        mutil: 'MT_RANK6_1',
        key: '',
        mainType: 'BTM_RANK_6',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '2',
        mutil: 'MT_RANK6_2',
        key: '',
        mainType: 'BTM_RANK_6',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '3',
        mutil: 'MT_RANK6_3',
        key: '',
        mainType: 'BTM_RANK_6',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '4',
        mutil: 'MT_RANK6_4',
        key: '',
        mainType: 'BTM_RANK_6',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '5',
        mutil: 'MT_RANK6_5',
        key: '',
        mainType: 'BTM_RANK_6',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '6',
        mutil: 'MT_RANK6_6',
        key: '',
        mainType: 'BTM_RANK_6',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '7',
        mutil: 'MT_RANK6_7',
        key: '',
        mainType: 'BTM_RANK_6',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '8',
        mutil: 'MT_RANK6_8',
        key: '',
        mainType: 'BTM_RANK_6',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '9',
        mutil: 'MT_RANK6_9',
        key: '',
        mainType: 'BTM_RANK_6',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '10',
        mutil: 'MT_RANK6_10',
        key: '',
        mainType: 'BTM_RANK_6',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      ///第七名
      {
        text: '1',
        mutil: 'MT_RANK7_1',
        key: '',
        mainType: 'BTM_RANK_7',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '2',
        mutil: 'MT_RANK7_2',
        key: '',
        mainType: 'BTM_RANK_7',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '3',
        mutil: 'MT_RANK7_3',
        key: '',
        mainType: 'BTM_RANK_7',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '4',
        mutil: 'MT_RANK7_4',
        key: '',
        mainType: 'BTM_RANK_7',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '5',
        mutil: 'MT_RANK7_5',
        key: '',
        mainType: 'BTM_RANK_7',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '6',
        mutil: 'MT_RANK7_6',
        key: '',
        mainType: 'BTM_RANK_7',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '7',
        mutil: 'MT_RANK7_7',
        key: '',
        mainType: 'BTM_RANK_7',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '8',
        mutil: 'MT_RANK7_8',
        key: '',
        mainType: 'BTM_RANK_7',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '9',
        mutil: 'MT_RANK7_9',
        key: '',
        mainType: 'BTM_RANK_7',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '10',
        mutil: 'MT_RANK7_10',
        key: '',
        mainType: 'BTM_RANK_7',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      ///第八名
      {
        text: '1',
        mutil: 'MT_RANK8_1',
        key: '',
        mainType: 'BTM_RANK_8',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '2',
        mutil: 'MT_RANK8_2',
        key: '',
        mainType: 'BTM_RANK_8',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '3',
        mutil: 'MT_RANK8_3',
        key: '',
        mainType: 'BTM_RANK_8',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '4',
        mutil: 'MT_RANK8_4',
        key: '',
        mainType: 'BTM_RANK_8',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '5',
        mutil: 'MT_RANK8_5',
        key: '',
        mainType: 'BTM_RANK_8',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '6',
        mutil: 'MT_RANK8_6',
        key: '',
        mainType: 'BTM_RANK_8',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '7',
        mutil: 'MT_RANK8_7',
        key: '',
        mainType: 'BTM_RANK_8',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '8',
        mutil: 'MT_RANK8_8',
        key: '',
        mainType: 'BTM_RANK_8',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '9',
        mutil: 'MT_RANK8_9',
        key: '',
        mainType: 'BTM_RANK_8',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '10',
        mutil: 'MT_RANK8_10',
        key: '',
        mainType: 'BTM_RANK_8',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      ///第九名
      {
        text: '1',
        mutil: 'MT_RANK9_1',
        key: '',
        mainType: 'BTM_RANK_9',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '2',
        mutil: 'MT_RANK9_2',
        key: '',
        mainType: 'BTM_RANK_9',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '3',
        mutil: 'MT_RANK9_3',
        key: '',
        mainType: 'BTM_RANK_9',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '4',
        mutil: 'MT_RANK9_4',
        key: '',
        mainType: 'BTM_RANK_9',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '5',
        mutil: 'MT_RANK9_5',
        key: '',
        mainType: 'BTM_RANK_9',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '6',
        mutil: 'MT_RANK9_6',
        key: '',
        mainType: 'BTM_RANK_9',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '7',
        mutil: 'MT_RANK9_7',
        key: '',
        mainType: 'BTM_RANK_9',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '8',
        mutil: 'MT_RANK9_8',
        key: '',
        mainType: 'BTM_RANK_9',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '9',
        mutil: 'MT_RANK9_9',
        key: '',
        mainType: 'BTM_RANK_9',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '10',
        mutil: 'MT_RANK9_10',
        key: '',
        mainType: 'BTM_RANK_9',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      ///第十名
      {
        text: '1',
        mutil: 'MT_RANK10_1',
        key: '',
        mainType: 'BTM_RANK_10',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '2',
        mutil: 'MT_RANK10_2',
        key: '',
        mainType: 'BTM_RANK_10',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '3',
        mutil: 'MT_RANK10_3',
        key: '',
        mainType: 'BTM_RANK_10',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '4',
        mutil: 'MT_RANK10_4',
        key: '',
        mainType: 'BTM_RANK_10',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '5',
        mutil: 'MT_RANK10_5',
        key: '',
        mainType: 'BTM_RANK_10',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '6',
        mutil: 'MT_RANK10_6',
        key: '',
        mainType: 'BTM_RANK_10',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '7',
        mutil: 'MT_RANK10_7',
        key: '',
        mainType: 'BTM_RANK_10',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '8',
        mutil: 'MT_RANK10_8',
        key: '',
        mainType: 'BTM_RANK_10',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '9',
        mutil: 'MT_RANK10_9',
        key: '',
        mainType: 'BTM_RANK_10',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '10',
        mutil: 'MT_RANK10_10',
        key: '',
        mainType: 'BTM_RANK_10',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
    ],
  },
  {
    title: '两面盘',
    paneKey: '2',
    list: [
      {
        text: '冠亚大',
        mutil: 'MT_SUM_DA',
        key: '',
        mainType: 'BTM_SUM',
        subMainType: 'SBTS_DA',
        topType: 'none',
        subTypeName: CMD_3102.emBetSubTypeNames[1],
        cls: styels['t-nomal'],
      },
      {
        text: '冠亚小',
        mutil: 'MT_SUM_XIAO',
        key: '',
        mainType: 'BTM_SUM',
        subMainType: 'SBTS_XIAO',
        topType: 'none',
        subTypeName: CMD_3102.emBetSubTypeNames[1],
        cls: styels['t-nomal'],
      },
      {
        text: '冠亚单',
        mutil: 'MT_SUM_DAN',
        key: '',
        mainType: 'BTM_SUM',
        subMainType: 'SBTS_DAN',
        topType: 'none',
        subTypeName: CMD_3102.emBetSubTypeNames[1],
        cls: styels['t-nomal'],
      },
      {
        text: '冠亚双',
        mutil: 'MT_SUM_SHUANG',
        key: '',
        mainType: 'BTM_SUM',
        subMainType: 'SBTS_SHUANG',
        topType: 'none',
        subTypeName: CMD_3102.emBetSubTypeNames[1],
        cls: styels['t-nomal'],
      },
      ///冠军大小单双龙虎
      {
        text: '大',
        mutil: 'MT_RANK_DA',
        key: '',
        mainType: 'BTM_SUM',
        subMainType: 'SBTR_DA',
        topType: 'none',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '小',
        mutil: 'MT_RANK_XIAO',
        key: '',
        mainType: 'BTM_SUM',
        subMainType: 'SBTR_XIAO',
        topType: 'none',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '单',
        mutil: 'MT_RANK_DAN',
        key: '',
        mainType: 'BTM_SUM',
        subMainType: 'SBTR_DAN',
        topType: 'none',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '双',
        mutil: 'MT_RANK_SHUANG',
        key: '',
        mainType: 'BTM_SUM',
        subMainType: 'SBTR_SHUANG',
        topType: 'none',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '龙',
        mutil: 'MT_RANK_LONG',
        key: '',
        mainType: 'BTM_SUM',
        subMainType: 'SBTR_LONG',
        topType: 'none',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '虎',
        mutil: 'MT_RANK_HU',
        key: '',
        mainType: 'BTM_SUM',
        subMainType: 'SBTR_HU',
        topType: 'none',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
    ]
  }

];
