import { CMD_2905 } from '@/engine/game/pc/2905/CMD_2905';

/**** 2905 澳洲幸运 *****/
export const firstBallList = {
  title: 'QIU_1',
  key: '1',
  list: [
    {
      text: 'DA',
      mutil: 'MT_D1_DA',
      key: '第一球-大',
      mainType: 'BTM_DING_1',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_DA',
      cls: '',
      type: '',
    },
    {
      text: 'XIAO',
      mutil: 'MT_D1_XIAO',
      key: '第一球-小',
      mainType: 'BTM_DING_1',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_XIAO',
      cls: '',
      type: '',
    },
    {
      text: 'DAN',
      mutil: 'MT_D1_DAN',
      key: '第一球-单',
      mainType: 'BTM_DING_1',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_DAN',
      cls: '',
      type: '',
    },
    {
      text: 'SHUANG',
      mutil: 'MT_D1_SHUANG',
      key: '第一球-双',
      mainType: 'BTM_DING_1',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_SHUANG',
      cls: '',
      type: '',
    },
    {
      text: '0',
      mutil: 'MT_D1_DIAN',
      key: '第一球-0',
      mainType: 'BTM_DING_1',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '1',
      mutil: 'MT_D1_DIAN',
      key: '第一球-1',
      mainType: 'BTM_DING_1',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '2',
      mutil: 'MT_D1_DIAN',
      key: '第一球-2',
      mainType: 'BTM_DING_1',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '3',
      mutil: 'MT_D1_DIAN',
      key: '第一球-3',
      mainType: 'BTM_DING_1',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '4',
      mutil: 'MT_D1_DIAN',
      key: '第一球-4',
      mainType: 'BTM_DING_1',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '5',
      mutil: 'MT_D1_DIAN',
      key: '第一球-5',
      mainType: 'BTM_DING_1',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '6',
      mutil: 'MT_D1_DIAN',
      key: '第一球-6',
      mainType: 'BTM_DING_1',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '7',
      mutil: 'MT_D1_DIAN',
      key: '第一球-7',
      mainType: 'BTM_DING_1',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '8',
      mutil: 'MT_D1_DIAN',
      key: '第一球-8',
      mainType: 'BTM_DING_1',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '9',
      mutil: 'MT_D1_DIAN',
      key: '第一球-9',
      mainType: 'BTM_DING_1',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
  ],
};

export const secBallList = {
  title: 'QIU_2',
  key: '2',
  list: [
    {
      text: 'DA',
      mutil: 'MT_D2_DA',
      key: '第二球-大',
      mainType: 'BTM_DING_2',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_DA',
      cls: '',
      type: '',
    },
    {
      text: 'XIAO',
      mutil: 'MT_D2_XIAO',
      key: '第二球-小',
      mainType: 'BTM_DING_2',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_XIAO',
      cls: '',
      type: '',
    },
    {
      text: 'DAN',
      mutil: 'MT_D2_DAN',
      key: '第二球-单',
      mainType: 'BTM_DING_2',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_DAN',
      cls: '',
      type: '',
    },
    {
      text: 'SHUANG',
      mutil: 'MT_D2_SHUANG',
      key: '第二球-双',
      mainType: 'BTM_DING_2',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_SHUANG',
      cls: '',
      type: '',
    },
    {
      text: '0',
      mutil: 'MT_D2_DIAN',
      key: '第二球-0',
      mainType: 'BTM_DING_2',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '1',
      mutil: 'MT_D2_DIAN',
      key: '第二球-1',
      mainType: 'BTM_DING_2',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '2',
      mutil: 'MT_D2_DIAN',
      key: '第二球-2',
      mainType: 'BTM_DING_2',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '3',
      mutil: 'MT_D2_DIAN',
      key: '第二球-3',
      mainType: 'BTM_DING_2',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '4',
      mutil: 'MT_D2_DIAN',
      key: '第二球-4',
      mainType: 'BTM_DING_2',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '5',
      mutil: 'MT_D2_DIAN',
      key: '第二球-5',
      mainType: 'BTM_DING_2',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '6',
      mutil: 'MT_D2_DIAN',
      key: '第二球-6',
      mainType: 'BTM_DING_2',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '7',
      mutil: 'MT_D2_DIAN',
      key: '第二球-7',
      mainType: 'BTM_DING_2',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '8',
      mutil: 'MT_D2_DIAN',
      key: '第二球-8',
      mainType: 'BTM_DING_2',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '9',
      mutil: 'MT_D2_DIAN',
      key: '第二球-9',
      mainType: 'BTM_DING_2',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
  ],
};

export const thrBallList = {
  title: 'QIU_3',
  key: '3',
  list: [
    {
      text: 'DA',
      mutil: 'MT_D3_DA',
      key: '第三球-大',
      mainType: 'BTM_DING_3',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_DA',
      cls: '',
      type: '',
    },
    {
      text: 'XIAO',
      mutil: 'MT_D3_XIAO',
      key: '第三球-小',
      mainType: 'BTM_DING_3',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_XIAO',
      cls: '',
      type: '',
    },
    {
      text: 'DAN',
      mutil: 'MT_D3_DAN',
      key: '第三球-单',
      mainType: 'BTM_DING_3',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_DAN',
      cls: '',
      type: '',
    },
    {
      text: 'SHUANG',
      mutil: 'MT_D3_SHUANG',
      key: '第三球-双',
      mainType: 'BTM_DING_3',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_SHUANG',
      cls: '',
      type: '',
    },
    {
      text: '0',
      mutil: 'MT_D3_DIAN',
      key: '第三球-0',
      mainType: 'BTM_DING_3',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '1',
      mutil: 'MT_D3_DIAN',
      key: '第三球-1',
      mainType: 'BTM_DING_3',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '2',
      mutil: 'MT_D3_DIAN',
      key: '第三球-2',
      mainType: 'BTM_DING_3',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '3',
      mutil: 'MT_D3_DIAN',
      key: '第三球-3',
      mainType: 'BTM_DING_3',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '4',
      mutil: 'MT_D3_DIAN',
      key: '第三球-4',
      mainType: 'BTM_DING_3',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '5',
      mutil: 'MT_D3_DIAN',
      key: '第三球-5',
      mainType: 'BTM_DING_3',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '6',
      mutil: 'MT_D3_DIAN',
      key: '第三球-6',
      mainType: 'BTM_DING_3',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '7',
      mutil: 'MT_D3_DIAN',
      key: '第三球-7',
      mainType: 'BTM_DING_3',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '8',
      mutil: 'MT_D3_DIAN',
      key: '第三球-8',
      mainType: 'BTM_DING_3',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '9',
      mutil: 'MT_D3_DIAN',
      key: '第三球-9',
      mainType: 'BTM_DING_3',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
  ],
};

export const fourBallList = {
  title: 'QIU_4',
  key: '4',
  list: [
    {
      text: 'DA',
      mutil: 'MT_D4_DA',
      key: '第四球-大',
      mainType: 'BTM_DING_4',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_DA',
      cls: '',
      type: '',
    },
    {
      text: 'XIAO',
      mutil: 'MT_D4_XIAO',
      key: '第四球-小',
      mainType: 'BTM_DING_4',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_XIAO',
      cls: '',
      type: '',
    },
    {
      text: 'DAN',
      mutil: 'MT_D4_DAN',
      key: '第四球-单',
      mainType: 'BTM_DING_4',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_DAN',
      cls: '',
      type: '',
    },
    {
      text: 'SHUANG',
      mutil: 'MT_D4_SHUANG',
      key: '第四球-双',
      mainType: 'BTM_DING_4',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_SHUANG',
      cls: '',
      type: '',
    },
    {
      text: '0',
      mutil: 'MT_D4_DIAN',
      key: '第四球-0',
      mainType: 'BTM_DING_4',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '1',
      mutil: 'MT_D4_DIAN',
      key: '第四球-1',
      mainType: 'BTM_DING_4',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '2',
      mutil: 'MT_D4_DIAN',
      key: '第四球-2',
      mainType: 'BTM_DING_4',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '3',
      mutil: 'MT_D4_DIAN',
      key: '第四球-3',
      mainType: 'BTM_DING_4',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '4',
      mutil: 'MT_D4_DIAN',
      key: '第四球-4',
      mainType: 'BTM_DING_4',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '5',
      mutil: 'MT_D4_DIAN',
      key: '第四球-5',
      mainType: 'BTM_DING_4',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '6',
      mutil: 'MT_D4_DIAN',
      key: '第四球-6',
      mainType: 'BTM_DING_4',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '7',
      mutil: 'MT_D4_DIAN',
      key: '第四球-7',
      mainType: 'BTM_DING_4',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '8',
      mutil: 'MT_D4_DIAN',
      key: '第四球-8',
      mainType: 'BTM_DING_4',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '9',
      mutil: 'MT_D4_DIAN',
      key: '第四球-9',
      mainType: 'BTM_DING_4',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
  ],
};

export const fiveBallList = {
  title: 'QIU_5',
  key: '5',
  list: [
    {
      text: 'DA',
      mutil: 'MT_D5_DA',
      key: '第五球-大',
      mainType: 'BTM_DING_5',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_DA',
      cls: '',
      type: '',
    },
    {
      text: 'XIAO',
      mutil: 'MT_D5_XIAO',
      key: '第五球-小',
      mainType: 'BTM_DING_5',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_XIAO',
      cls: '',
      type: '',
    },
    {
      text: 'DAN',
      mutil: 'MT_D5_DAN',
      key: '第五球-单',
      mainType: 'BTM_DING_5',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_DAN',
      cls: '',
      type: '',
    },
    {
      text: 'SHUANG',
      mutil: 'MT_D5_SHUANG',
      key: '第五球-双',
      mainType: 'BTM_DING_5',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_SHUANG',
      cls: '',
      type: '',
    },
    {
      text: '0',
      mutil: 'MT_D5_DIAN',
      key: '第五球-0',
      mainType: 'BTM_DING_5',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '1',
      mutil: 'MT_D5_DIAN',
      key: '第五球-1',
      mainType: 'BTM_DING_5',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '2',
      mutil: 'MT_D5_DIAN',
      key: '第五球-2',
      mainType: 'BTM_DING_5',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '3',
      mutil: 'MT_D5_DIAN',
      key: '第五球-3',
      mainType: 'BTM_DING_5',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '4',
      mutil: 'MT_D5_DIAN',
      key: '第五球-4',
      mainType: 'BTM_DING_5',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '5',
      mutil: 'MT_D5_DIAN',
      key: '第五球-5',
      mainType: 'BTM_DING_5',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '6',
      mutil: 'MT_D5_DIAN',
      key: '第五球-6',
      mainType: 'BTM_DING_5',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '7',
      mutil: 'MT_D5_DIAN',
      key: '第五球-7',
      mainType: 'BTM_DING_5',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '8',
      mutil: 'MT_D5_DIAN',
      key: '第五球-8',
      mainType: 'BTM_DING_5',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
    {
      text: '9',
      mutil: 'MT_D5_DIAN',
      key: '第五球-9',
      mainType: 'BTM_DING_5',
      subTypeName: CMD_2905.emBetSubTypeNames[1],
      subMainType: 'SBTD_NUM',
      cls: '',
      type: 'single',
    },
  ],
};

export const sumBallList = {
  title: 'ZONGHE_LONGHU',
  key: '-1',
  list: [
    {
      text: 'ZONGHEDA',
      mutil: 'MT_H_DA',
      key: '总和-大',
      mainType: 'BTM_HE',
      subTypeName: CMD_2905.emBetSubTypeNames[0],
      subMainType: 'SBTH_DA',
      cls: '',
      type: '',
    },
    {
      text: 'ZONGHEXIAO',
      mutil: 'MT_H_XIAO',
      key: '总和-小',
      mainType: 'BTM_HE',
      subTypeName: CMD_2905.emBetSubTypeNames[0],
      subMainType: 'SBTH_XIAO',
      cls: '',
      type: '',
    },
    {
      text: 'ZONGHEDAN',
      mutil: 'MT_H_DAN',
      key: '总和-单',
      mainType: 'BTM_HE',
      subTypeName: CMD_2905.emBetSubTypeNames[0],
      subMainType: 'SBTH_DAN',
      cls: '',
      type: '',
    },
    {
      text: 'ZONGHESHUANG',
      mutil: 'MT_H_SHUANG',
      key: '总和-双',
      mainType: 'BTM_HE',
      subTypeName: CMD_2905.emBetSubTypeNames[0],
      subMainType: 'SBTH_SHUANG',
      cls: '',
      type: '',
    },
    {
      text: 'LONG',
      mutil: 'MT_H_LONG',
      key: '总和-龙',
      mainType: 'BTM_HE',
      subTypeName: CMD_2905.emBetSubTypeNames[0],
      subMainType: 'SBTH_LONG',
      cls: '',
      type: '',
    },
    {
      text: 'HU',
      mutil: 'MT_H_HU',
      key: '总和-虎',
      mainType: 'BTM_HE',
      subTypeName: CMD_2905.emBetSubTypeNames[0],
      subMainType: 'SBTH_HU',
      cls: '',
      type: '',
    },
    {
      text: 'HE',
      mutil: 'MT_H_HE',
      key: '总和-和',
      mainType: 'BTM_HE',
      subTypeName: CMD_2905.emBetSubTypeNames[0],
      subMainType: 'SBTH_HE',
      cls: 'w-full',
    },
  ],
};

export const frontBallList = {
  title: 'QIANSAN',
  key: '6',
  list: [
    {
      text: 'BAOZI',
      mutil: 'MT_SAN_QIAN_BAO',
      key: '前三-豹子',
      mainType: 'BTM_SAN_QIAN',
      subTypeName: CMD_2905.emBetSubTypeNames[2],
      subMainType: 'SBTS_BAO',
      cls: '',
      type: '',
    },
    {
      text: 'SHUNZI',
      mutil: 'MT_SAN_QIAN_SHUN',
      key: '前三-顺子',
      mainType: 'BTM_SAN_QIAN',
      subTypeName: CMD_2905.emBetSubTypeNames[2],
      subMainType: 'SBTS_SHUN',
      cls: '',
      type: '',
    },
    {
      text: 'DUIZI',
      mutil: 'MT_SAN_QIAN_DUI',
      key: '前三-对子',
      mainType: 'BTM_SAN_QIAN',
      subTypeName: CMD_2905.emBetSubTypeNames[2],
      subMainType: 'SBTS_DUI',
      cls: '',
      type: '',
    },
    {
      text: 'BANSHUN',
      mutil: 'MT_SAN_QIAN_BAN',
      key: '前三-半顺',
      mainType: 'BTM_SAN_QIAN',
      subTypeName: CMD_2905.emBetSubTypeNames[2],
      subMainType: 'SBTS_BAN',
      cls: '',
      type: '',
    },
    {
      text: 'ZANLIU',
      mutil: 'MT_SAN_QIAN_ZA',
      key: '前三-杂六',
      mainType: 'BTM_SAN_QIAN',
      subTypeName: CMD_2905.emBetSubTypeNames[2],
      subMainType: 'SBTS_ZA',
      cls: 'w-full',
    },
  ],
};

export const centerBallList = {
  title: 'ZHOGN_SAN',
  key: '7',
  list: [
    {
      text: 'BAOZI',
      mutil: 'MT_SAN_ZHONG_BAO',
      key: '中三-豹子',
      mainType: 'BTM_SAN_ZHONG',
      subTypeName: CMD_2905.emBetSubTypeNames[2],
      subMainType: 'SBTS_BAO',
      cls: '',
      type: '',
    },
    {
      text: 'SHUNZI',
      mutil: 'MT_SAN_ZHONG_SHUN',
      key: '中三-顺子',
      mainType: 'BTM_SAN_ZHONG',
      subTypeName: CMD_2905.emBetSubTypeNames[2],
      subMainType: 'SBTS_SHUN',
      cls: '',
      type: '',
    },
    {
      text: 'DUIZI',
      mutil: 'MT_SAN_ZHONG_DUI',
      key: '中三-对子',
      mainType: 'BTM_SAN_ZHONG',
      subTypeName: CMD_2905.emBetSubTypeNames[2],
      subMainType: 'SBTS_DUI',
      cls: '',
      type: '',
    },
    {
      text: 'BANSHUN',
      mutil: 'MT_SAN_ZHONG_BAN',
      key: '中三-半顺',
      mainType: 'BTM_SAN_ZHONG',
      subTypeName: CMD_2905.emBetSubTypeNames[2],
      subMainType: 'SBTS_BAN',
      cls: '',
      type: '',
    },
    {
      text: 'ZANLIU',
      mutil: 'MT_SAN_ZHONG_ZA',
      key: '中三-杂六',
      mainType: 'BTM_SAN_ZHONG',
      subTypeName: CMD_2905.emBetSubTypeNames[2],
      subMainType: 'SBTS_ZA',
      cls: 'w-full',
    },
  ],
};

export const afterBallList = {
  title: '后三',
  key: '8',
  list: [
    {
      text: 'BAOZI',
      mutil: 'MT_SAN_HOU_BAO',
      key: '后三-豹子',
      mainType: 'BTM_SAN_HOU',
      subTypeName: CMD_2905.emBetSubTypeNames[2],
      subMainType: 'SBTS_BAO',
      cls: '',
      type: '',
    },
    {
      text: 'SHUNZI',
      mutil: 'MT_SAN_HOU_SHUN',
      key: '后三-顺子',
      mainType: 'BTM_SAN_HOU',
      subTypeName: CMD_2905.emBetSubTypeNames[2],
      subMainType: 'SBTS_SHUN',
      cls: '',
      type: '',
    },
    {
      text: 'DUIZI',
      mutil: 'MT_SAN_HOU_DUI',
      key: '顺子-对子',
      mainType: 'BTM_SAN_HOU',
      subTypeName: CMD_2905.emBetSubTypeNames[2],
      subMainType: 'SBTS_DUI',
      cls: '',
      type: '',
    },
    {
      text: 'BANSHUN',
      mutil: 'MT_SAN_HOU_BAN',
      key: '顺子-半顺',
      mainType: 'BTM_SAN_HOU',
      subTypeName: CMD_2905.emBetSubTypeNames[2],
      subMainType: 'SBTS_BAN',
      cls: '',
      type: '',
    },
    {
      text: 'ZANLIU',
      mutil: 'MT_SAN_HOU_ZA',
      key: '顺子-杂六',
      mainType: 'BTM_SAN_HOU',
      subTypeName: CMD_2905.emBetSubTypeNames[2],
      subMainType: 'SBTS_ZA',
      cls: 'w-full',
    },
  ],
};

export const bullfightBallList = {
  title: 'DOU_NIU',
  key: '9',
  list: [
    {
      text: 'NIUNIU',
      /**
       * 赔率枚举的key
       */
      mutil: 'MT_NIU_10',
      /**
       * 名称
       */
      key: '斗牛-牛牛',
      /**
       * 主类型枚举的key
       */
      mainType: 'BTM_NIU',
      /**
       * 子类型枚举类的名称
       */
      subTypeName: CMD_2905.emBetSubTypeNames[3],
      /**
       * 子类型枚举的key
       */
      subMainType: 'SBTN_NUM',
      cls: '',
      type: '',
      num: 10,
    },
    {
      text: 'NIUJIU',
      mutil: 'MT_NIU_9',
      key: '斗牛-牛九',
      mainType: 'BTM_NIU',
      subTypeName: CMD_2905.emBetSubTypeNames[3],
      subMainType: 'SBTN_NUM',
      cls: '',
      type: '',
      num: 9
    },
    {
      text: 'NIUBA',
      mutil: 'MT_NIU_8',
      key: '斗牛-牛八',
      mainType: 'BTM_NIU',
      subTypeName: CMD_2905.emBetSubTypeNames[3],
      subMainType: 'SBTN_NUM',
      cls: '',
      type: '',
      num: 8
    },
    {
      text: 'NIUQI',
      mutil: 'MT_NIU_7',
      key: '斗牛-牛七',
      mainType: 'BTM_NIU',
      subTypeName: CMD_2905.emBetSubTypeNames[3],
      subMainType: 'SBTN_NUM',
      cls: '',
      type: '',
      num: 7
    },
    {
      text: 'NIULIU',
      mutil: 'MT_NIU_6',
      key: '斗牛-牛六',
      mainType: 'BTM_NIU',
      subTypeName: CMD_2905.emBetSubTypeNames[3],
      subMainType: 'SBTN_NUM',
      cls: '',
      type: '',
      num: 6
    },
    {
      text: 'NIUWU',
      mutil: 'MT_NIU_5',
      key: '斗牛-牛五',
      mainType: 'BTM_NIU',
      subTypeName: CMD_2905.emBetSubTypeNames[3],
      subMainType: 'SBTN_NUM',
      cls: '',
      type: '',
      num: 5
    },
    {
      text: 'NIUSI',
      mutil: 'MT_NIU_4',
      key: '斗牛-牛四',
      mainType: 'BTM_NIU',
      subTypeName: CMD_2905.emBetSubTypeNames[3],
      subMainType: 'SBTN_NUM',
      cls: '',
      type: '',
      num: 4
    },
    {
      text: 'NIUSAN',
      mutil: 'MT_NIU_3',
      key: '斗牛-牛三',
      mainType: 'BTM_NIU',
      subTypeName: CMD_2905.emBetSubTypeNames[3],
      subMainType: 'SBTN_NUM',
      cls: '',
      type: '',
      num: 3
    },
    {
      text: 'NIUER',
      mutil: 'MT_NIU_2',
      key: '斗牛-牛二',
      mainType: 'BTM_NIU',
      subTypeName: CMD_2905.emBetSubTypeNames[3],
      subMainType: 'SBTN_NUM',
      cls: '',
      type: '',
      num: 2
    },
    {
      text: 'NIUYI',
      mutil: 'MT_NIU_1',
      key: '斗牛-牛一',
      mainType: 'BTM_NIU',
      subTypeName: CMD_2905.emBetSubTypeNames[3],
      subMainType: 'SBTN_NUM',
      cls: '',
      type: '',
      num: 1
    },
    {
      text: 'WUNIU',
      mutil: 'MT_NIU_0',
      key: '斗牛-无牛',
      mainType: 'BTM_NIU',
      subTypeName: CMD_2905.emBetSubTypeNames[3],
      subMainType: 'SBTN_NUM',
      cls: 'w-full',
      type: '',
      num: 0
    },
    {
      text: 'NIUDA',
      mutil: 'MT_NIU_DA',
      key: '斗牛-牛大',
      mainType: 'BTM_NIU',
      subTypeName: CMD_2905.emBetSubTypeNames[3],
      subMainType: 'SBTN_DA',
      cls: '',
      type: '',
    },
    {
      text: 'NIUXIAO',
      mutil: 'MT_NIU_XIAO',
      key: '斗牛-牛小',
      mainType: 'BTM_NIU',
      subTypeName: CMD_2905.emBetSubTypeNames[3],
      subMainType: 'SBTN_XIAO',
      cls: '',
      type: '',
    },
    {
      text: 'NIUDAN',
      mutil: 'MT_NIU_DAN',
      key: '斗牛-牛单',
      mainType: 'BTM_NIU',
      subTypeName: CMD_2905.emBetSubTypeNames[3],
      subMainType: 'SBTN_DAN',
      cls: '',
      type: '',
    },
    {
      text: 'NIUSHUANG',
      mutil: 'MT_NIU_SHUANG',
      key: '斗牛-牛双',
      mainType: 'BTM_NIU',
      subTypeName: CMD_2905.emBetSubTypeNames[3],
      subMainType: 'SBTN_SHUANG',
      cls: '',
      type: '',
    },
    {
      text: 'WUTIAO',
      mutil: 'MT_NIU_TIAO_5',
      key: '斗牛梭哈-五条',
      mainType: 'BTM_NIU',
      subTypeName: CMD_2905.emBetSubTypeNames[3],
      subMainType: 'SBTN_TIAO_5',
      cls: '',
      type: '',
    },
    {
      text: 'SITIAO',
      mutil: 'MT_NIU_TIAO_4',
      key: '斗牛梭哈-四条',
      mainType: 'BTM_NIU',
      subTypeName: CMD_2905.emBetSubTypeNames[3],
      subMainType: 'SBTN_TIAO_4',
      cls: '',
      type: '',
    },
    {
      text: 'HULU',
      mutil: 'MT_NIU_HULU',
      key: '斗牛梭哈-葫芦',
      mainType: 'BTM_NIU',
      subTypeName: CMD_2905.emBetSubTypeNames[3],
      subMainType: 'SBTN_HULU',
      cls: '',
      type: '',
    },
    {
      text: 'SHUNZI',
      mutil: 'MT_NIU_SHUN',
      key: '斗牛梭哈-顺子',
      mainType: 'BTM_NIU',
      subTypeName: CMD_2905.emBetSubTypeNames[3],
      subMainType: 'SBTN_SHUN',
      cls: '',
      type: '',
    },
    {
      text: 'SANTIAO',
      mutil: 'MT_NIU_TIAO_3',
      key: '斗牛梭哈-三条',
      mainType: 'BTM_NIU',
      subTypeName: CMD_2905.emBetSubTypeNames[3],
      subMainType: 'SBTN_TIAO_3',
      cls: '',
      type: '',
    },
    {
      text: 'ERDUI',
      mutil: 'MT_NIU_DUI_2',
      key: '斗牛梭哈-两对',
      mainType: 'BTM_NIU',
      subTypeName: CMD_2905.emBetSubTypeNames[3],
      subMainType: 'SBTN_DUI_2',
      cls: '',
      type: '',
    },
    {
      text: 'YIDUI',
      mutil: 'MT_NIU_DUI_1',
      key: '斗牛梭哈-一对',
      mainType: 'BTM_NIU',
      subTypeName: CMD_2905.emBetSubTypeNames[3],
      subMainType: 'SBTN_DUI_1',
      cls: '',
      type: '',
    },
    {
      text: 'GAOPAI',
      mutil: 'MT_NIU_GAO',
      key: '斗牛梭哈-高牌',
      mainType: 'BTM_NIU',
      subTypeName: CMD_2905.emBetSubTypeNames[3],
      subMainType: 'SBTN_GAO',
      cls: '',
      type: '',
    },
  ],
};

// ###################################################内容区
// 整合
export const conformityTab = [sumBallList, firstBallList, secBallList, thrBallList, fourBallList, fiveBallList, frontBallList, centerBallList, afterBallList];

export const firstBallTab = [
  {
    ...firstBallList,
    title: 'QIUHAO',
    list: firstBallList.list.filter((r) => r.subMainType === 'SBTD_NUM'),
  },
  {
    ...sumBallList,
    title: 'LIANGMIAN',
    list: [...firstBallList.list.filter((r) => r.subMainType !== 'SBTD_NUM'), ...sumBallList.list],
  },
  frontBallList,
  centerBallList,
  afterBallList,
];

export const secBallTab = [
  {
    ...secBallList,
    title: 'QIUHAO',
    list: secBallList.list.filter((r) => r.subMainType === 'SBTD_NUM'),
  },
  {
    ...sumBallList,
    title: 'LIANGMIAN',
    list: [...secBallList.list.filter((r) => r.subMainType !== 'SBTD_NUM'), ...sumBallList.list],
  },
  frontBallList,
  centerBallList,
  afterBallList,
];

export const thrBallTab = [
  {
    ...thrBallList,
    title: 'QIUHAO',
    list: thrBallList.list.filter((r) => r.subMainType === 'SBTD_NUM'),
  },
  {
    ...sumBallList,
    title: 'LIANGMIAN',
    list: [...thrBallList.list.filter((r) => r.subMainType !== 'SBTD_NUM'), ...sumBallList.list],
  },
  frontBallList,
  centerBallList,
  afterBallList,
];

export const fourBallTab = [
  {
    ...fourBallList,
    title: 'QIUHAO',
    list: fourBallList.list.filter((r) => r.subMainType === 'SBTD_NUM'),
  },
  {
    ...sumBallList,
    title: 'LIANGMIAN',
    list: [...fourBallList.list.filter((r) => r.subMainType !== 'SBTD_NUM'), ...sumBallList.list],
  },
  frontBallList,
  centerBallList,
  afterBallList,
];

export const fiveBallTab = [
  {
    ...fiveBallList,
    title: 'QIUHAO',
    list: fiveBallList.list.filter((r) => r.subMainType === 'SBTD_NUM'),
  },
  {
    ...sumBallList,
    title: 'LIANGMIAN',
    list: [...fiveBallList.list.filter((r) => r.subMainType !== 'SBTD_NUM'), ...sumBallList.list],
  },
  frontBallList,
  centerBallList,
  afterBallList,
];

export const bullfightTab = [
  { ...bullfightBallList, list: bullfightBallList.list.filter((r) => r.subMainType === 'SBTN_NUM') },
  {
    ...bullfightBallList,
    key: `${bullfightBallList.key}1`,
    title: 'DOUNIULIANGMIAN',
    list: bullfightBallList.list.filter((r) => ['SBTN_DA', 'SBTN_XIAO', 'SBTN_DAN', 'SBTN_SHUANG'].includes(r.subMainType)),
  },
  {
    ...bullfightBallList,
    key: `${bullfightBallList.key}2`,
    title: 'DOUNIUSHUOHA',
    list: bullfightBallList.list.filter((r) => ['SBTN_TIAO_5', 'SBTN_TIAO_4', 'SBTN_HULU', 'SBTN_SHUN', 'SBTN_TIAO_3', 'SBTN_DUI_2', 'SBTN_DUI_1', 'SBTN_GAO'].includes(r.subMainType)),
  },
];

export const quickTab = [firstBallList, secBallList, thrBallList, fourBallList, fiveBallList];
