import { CMD_3102 } from '@/engine/game/pc/3102/CMD_3102';
import styels from '../index.module.scss';

// 特码tab标题及内容
export const tabListFirst = [
  {
    title: 'NUMBER_1',
    key: '1',
    listKey: 'firstArr',
  },
  {
    title: 'NUMBER_2',
    key: '2',
    listKey: 'secArr',
  },
  {
    title: 'NUMBER_3',
    key: '3',
    listKey: 'thirArr',
  },
  {
    title: 'NUMBER_4',
    key: '4',
    listKey: 'forthArr',
  },
  {
    title: 'NUMBER_5',
    key: '5',
    listKey: 'fifthArr',
  },
  {
    title: 'NUMBER_6',
    key: '6',
    listKey: 'sixArr',
  },
  {
    title: 'NUMBER_7',
    key: '7',
    listKey: 'sevArr',
  },
  {
    title: 'NUMBER_8',
    key: '8',
    listKey: 'eightArr',
  },
  {
    title: 'NUMBER_9',
    key: '9',
    listKey: 'nineArr',
  },
  {
    title: 'NUMBER_10',
    key: '10',
    listKey: 'tenArr',
  },
];

export const tabListSecond = [
  {
    title: 'NUMBER_1_2_HE',
    key: '1',
    listKey: 'fsArr',
  },
  {
    title: 'NUMBER_1',
    key: '2',
    listKey: 'fsArr_1',
  },
  {
    title: 'NUMBER_2',
    key: '3',
    listKey: 'fsArr_2',
  },
  {
    title: 'NUMBER_3',
    key: '4',
    listKey: 'fsArr_3',
  },
  {
    title: 'NUMBER_4',
    key: '5',
    listKey: 'fsArr_4',
  },
  {
    title: 'NUMBER_5',
    key: '6',
    listKey: 'fsArr_5',
  },
  {
    title: 'NUMBER_6',
    key: '7',
    listKey: 'fsArr_6',
  },
  {
    title: 'NUMBER_7',
    key: '8',
    listKey: 'fsArr_7',
  },
  {
    title: 'NUMBER_8',
    key: '9',
    listKey: 'fsArr_8',
  },
  {
    title: 'NUMBER_9',
    key: '10',
    listKey: 'fsArr_9',
  },
  {
    title: 'NUMBER_10',
    key: '11',
    listKey: 'fsArr_10',
  },
];

export const tabListThird = [
  {
    title: 'NUMBER_1_2_HE',
    key: '1',
    listKey: 'fsSubArr',
  },
  {
    title: 'NUMBER_1',
    key: '2',
    listKey: 'fsSubArr_1',
  },
  {
    title: 'NUMBER_2',
    key: '3',
    listKey: 'fsSubArr_2',
  },
];

export const tabListForth = [
  {
    title: '', //冠亚组合
    key: '1',
    listKey: 'fsComArr',
  },
];

export const tabListFifth = [
  {
    title: 'NUMBER_1',
    key: '1',
    listKey: 'fsRank_1',
  },
  {
    title: 'NUMBER_2',
    key: '2',
    listKey: 'fsRank_2',
  },
  {
    title: 'NUMBER_3',
    key: '3',
    listKey: 'fsRank_3',
  },
  {
    title: 'NUMBER_4',
    key: '4',
    listKey: 'fsRank_4',
  },
  {
    title: 'NUMBER_5',
    key: '5',
    listKey: 'fsRank_5',
  },
];

export const tabListSixth = [
  {
    title: 'NUMBER_6',
    key: '1',
    listKey: 'fsRank_6',
  },
  {
    title: 'NUMBER_7',
    key: '2',
    listKey: 'fsRank_7',
  },
  {
    title: 'NUMBER_8',
    key: '3',
    listKey: 'fsRank_8',
  },
  {
    title: 'NUMBER_9',
    key: '4',
    listKey: 'fsRank_9',
  },
  {
    title: 'NUMBER_10',
    key: '5',
    listKey: 'fsRank_10',
  },
];

const lmSixCom = [{
  text: 'DA',
  mutil: 'MT_RANK_DA',
  key: '',
  mainType: 'BTM_RANK_1',
  subMainType: 'SBTR_DA',
  topType: 'none',
  subTypeName: CMD_3102.emBetSubTypeNames[0],
  cls: styels['t-nomal'],
},
{
  text: 'XIAO',
  mutil: 'MT_RANK_XIAO',
  key: '',
  mainType: 'BTM_RANK_1',
  subMainType: 'SBTR_XIAO',
  topType: 'none',
  subTypeName: CMD_3102.emBetSubTypeNames[0],
  cls: styels['t-large'],
},
{
  text: 'DAN',
  mutil: 'MT_RANK_DAN',
  key: '',
  mainType: 'BTM_RANK_1',
  subMainType: 'SBTR_DAN',
  topType: 'none',
  subTypeName: CMD_3102.emBetSubTypeNames[0],
  cls: styels['t-large'],
},
{
  text: 'SHUANG',
  mutil: 'MT_RANK_SHUANG',
  key: '',
  mainType: 'BTM_RANK_1',
  subMainType: 'SBTR_SHUANG',
  topType: 'none',
  subTypeName: CMD_3102.emBetSubTypeNames[0],
  cls: styels['t-large'],
},
{
  text: 'LONG',
  mutil: 'MT_RANK_LONG',
  key: '',
  mainType: 'BTM_RANK_1',
  subMainType: 'SBTR_LONG',
  topType: 'none',
  subTypeName: CMD_3102.emBetSubTypeNames[0],
  cls: styels['t-large'],
},
{
  text: 'HU',
  mutil: 'MT_RANK_HU',
  key: '',
  mainType: 'BTM_RANK_1',
  subMainType: 'SBTR_HU',
  topType: 'none',
  subTypeName: CMD_3102.emBetSubTypeNames[0],
  cls: styels['t-large'],
  }];

const lmFourCom = [{
  text: 'DA',
  mutil: 'MT_RANK_DA',
  key: '',
  mainType: 'BTM_SUM',
  subMainType: 'SBTR_DA',
  topType: 'none',
  subTypeName: CMD_3102.emBetSubTypeNames[0],
  cls: styels['t-nomal'],
},
{
  text: 'XIAO',
  mutil: 'MT_RANK_XIAO',
  key: '',
  mainType: 'BTM_SUM',
  subMainType: 'SBTR_XIAO',
  topType: 'none',
  subTypeName: CMD_3102.emBetSubTypeNames[0],
  cls: styels['t-large'],
},
{
  text: 'DAN',
  mutil: 'MT_RANK_DAN',
  key: '',
  mainType: 'BTM_SUM',
  subMainType: 'SBTR_DAN',
  topType: 'none',
  subTypeName: CMD_3102.emBetSubTypeNames[0],
  cls: styels['t-large'],
},
{
  text: 'SHUANG',
  mutil: 'MT_RANK_SHUANG',
  key: '',
  mainType: 'BTM_SUM',
  subMainType: 'SBTR_SHUANG',
  topType: 'none',
  subTypeName: CMD_3102.emBetSubTypeNames[0],
  cls: styels['t-large'],
}];

export const getLmSixTitle = (intoMainType?) => { 
  const newLmCom = lmSixCom.map((item) => ({
      ...item,
      mainType: intoMainType
  }));
  return newLmCom;
};

export const getLmFourTitle = (intoMainType?) => { 
  const newLmCom = lmFourCom.map((item) => ({
      ...item,
      mainType: intoMainType
  }));
  return newLmCom;
};

export const betNumberList = [
  {
    title: 'DIGHT_PAN',
    paneKey: '1',
    list: [
      {
        text: '1',
        mutil: 'MT_RANK1_1',
        key: '',
        mainType: 'BTM_RANK_1',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '2',
        mutil: 'MT_RANK1_2',
        key: '',
        mainType: 'BTM_RANK_1',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '3',
        mutil: 'MT_RANK1_3',
        key: '',
        mainType: 'BTM_RANK_1',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '4',
        mutil: 'MT_RANK1_4',
        key: '',
        mainType: 'BTM_RANK_1',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '5',
        mutil: 'MT_RANK1_5',
        key: '',
        mainType: 'BTM_RANK_1',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '6',
        mutil: 'MT_RANK1_6',
        key: '',
        mainType: 'BTM_RANK_1',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '7',
        mutil: 'MT_RANK1_7',
        key: '',
        mainType: 'BTM_RANK_1',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '8',
        mutil: 'MT_RANK1_8',
        key: '',
        mainType: 'BTM_RANK_1',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '9',
        mutil: 'MT_RANK1_9',
        key: '',
        mainType: 'BTM_RANK_1',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '10',
        mutil: 'MT_RANK1_10',
        key: '',
        mainType: 'BTM_RANK_1',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },

      /////////////////亚军
      {
        text: '1',
        mutil: 'MT_RANK2_1',
        key: '',
        mainType: 'BTM_RANK_2',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '2',
        mutil: 'MT_RANK2_2',
        key: '',
        mainType: 'BTM_RANK_2',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '3',
        mutil: 'MT_RANK2_3',
        key: '',
        mainType: 'BTM_RANK_2',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '4',
        mutil: 'MT_RANK2_4',
        key: '',
        mainType: 'BTM_RANK_2',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '5',
        mutil: 'MT_RANK2_5',
        key: '',
        mainType: 'BTM_RANK_2',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '6',
        mutil: 'MT_RANK2_6',
        key: '',
        mainType: 'BTM_RANK_2',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '7',
        mutil: 'MT_RANK2_7',
        key: '',
        mainType: 'BTM_RANK_2',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '8',
        mutil: 'MT_RANK2_8',
        key: '',
        mainType: 'BTM_RANK_2',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '9',
        mutil: 'MT_RANK2_9',
        key: '',
        mainType: 'BTM_RANK_2',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '10',
        mutil: 'MT_RANK2_10',
        key: '',
        mainType: 'BTM_RANK_2',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      /// 第三名
      {
        text: '1',
        mutil: 'MT_RANK3_1',
        key: '',
        mainType: 'BTM_RANK_3',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '2',
        mutil: 'MT_RANK3_2',
        key: '',
        mainType: 'BTM_RANK_3',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '3',
        mutil: 'MT_RANK3_3',
        key: '',
        mainType: 'BTM_RANK_3',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '4',
        mutil: 'MT_RANK3_4',
        key: '',
        mainType: 'BTM_RANK_3',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '5',
        mutil: 'MT_RANK3_5',
        key: '',
        mainType: 'BTM_RANK_3',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '6',
        mutil: 'MT_RANK3_6',
        key: '',
        mainType: 'BTM_RANK_3',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '7',
        mutil: 'MT_RANK3_7',
        key: '',
        mainType: 'BTM_RANK_3',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '8',
        mutil: 'MT_RANK3_8',
        key: '',
        mainType: 'BTM_RANK_3',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '9',
        mutil: 'MT_RANK3_9',
        key: '',
        mainType: 'BTM_RANK_3',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '10',
        mutil: 'MT_RANK3_10',
        key: '',
        mainType: 'BTM_RANK_3',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      ////第四名
      {
        text: '1',
        mutil: 'MT_RANK4_1',
        key: '',
        mainType: 'BTM_RANK_4',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '2',
        mutil: 'MT_RANK4_2',
        key: '',
        mainType: 'BTM_RANK_4',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '3',
        mutil: 'MT_RANK4_3',
        key: '',
        mainType: 'BTM_RANK_4',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '4',
        mutil: 'MT_RANK4_4',
        key: '',
        mainType: 'BTM_RANK_4',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '5',
        mutil: 'MT_RANK4_5',
        key: '',
        mainType: 'BTM_RANK_4',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '6',
        mutil: 'MT_RANK4_6',
        key: '',
        mainType: 'BTM_RANK_4',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '7',
        mutil: 'MT_RANK4_7',
        key: '',
        mainType: 'BTM_RANK_4',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '8',
        mutil: 'MT_RANK4_8',
        key: '',
        mainType: 'BTM_RANK_4',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '9',
        mutil: 'MT_RANK4_9',
        key: '',
        mainType: 'BTM_RANK_4',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '10',
        mutil: 'MT_RANK4_10',
        key: '',
        mainType: 'BTM_RANK_4',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      ///第五名
      {
        text: '1',
        mutil: 'MT_RANK5_1',
        key: '',
        mainType: 'BTM_RANK_5',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '2',
        mutil: 'MT_RANK5_2',
        key: '',
        mainType: 'BTM_RANK_5',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '3',
        mutil: 'MT_RANK5_3',
        key: '',
        mainType: 'BTM_RANK_5',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '4',
        mutil: 'MT_RANK5_4',
        key: '',
        mainType: 'BTM_RANK_5',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '5',
        mutil: 'MT_RANK5_5',
        key: '',
        mainType: 'BTM_RANK_5',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '6',
        mutil: 'MT_RANK5_6',
        key: '',
        mainType: 'BTM_RANK_5',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '7',
        mutil: 'MT_RANK5_7',
        key: '',
        mainType: 'BTM_RANK_5',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '8',
        mutil: 'MT_RANK5_8',
        key: '',
        mainType: 'BTM_RANK_5',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '9',
        mutil: 'MT_RANK5_9',
        key: '',
        mainType: 'BTM_RANK_5',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '10',
        mutil: 'MT_RANK5_10',
        key: '',
        mainType: 'BTM_RANK_5',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      ////第六名
      {
        text: '1',
        mutil: 'MT_RANK6_1',
        key: '',
        mainType: 'BTM_RANK_6',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '2',
        mutil: 'MT_RANK6_2',
        key: '',
        mainType: 'BTM_RANK_6',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '3',
        mutil: 'MT_RANK6_3',
        key: '',
        mainType: 'BTM_RANK_6',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '4',
        mutil: 'MT_RANK6_4',
        key: '',
        mainType: 'BTM_RANK_6',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '5',
        mutil: 'MT_RANK6_5',
        key: '',
        mainType: 'BTM_RANK_6',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '6',
        mutil: 'MT_RANK6_6',
        key: '',
        mainType: 'BTM_RANK_6',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '7',
        mutil: 'MT_RANK6_7',
        key: '',
        mainType: 'BTM_RANK_6',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '8',
        mutil: 'MT_RANK6_8',
        key: '',
        mainType: 'BTM_RANK_6',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '9',
        mutil: 'MT_RANK6_9',
        key: '',
        mainType: 'BTM_RANK_6',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '10',
        mutil: 'MT_RANK6_10',
        key: '',
        mainType: 'BTM_RANK_6',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      ///第七名
      {
        text: '1',
        mutil: 'MT_RANK7_1',
        key: '',
        mainType: 'BTM_RANK_7',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '2',
        mutil: 'MT_RANK7_2',
        key: '',
        mainType: 'BTM_RANK_7',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '3',
        mutil: 'MT_RANK7_3',
        key: '',
        mainType: 'BTM_RANK_7',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '4',
        mutil: 'MT_RANK7_4',
        key: '',
        mainType: 'BTM_RANK_7',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '5',
        mutil: 'MT_RANK7_5',
        key: '',
        mainType: 'BTM_RANK_7',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '6',
        mutil: 'MT_RANK7_6',
        key: '',
        mainType: 'BTM_RANK_7',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '7',
        mutil: 'MT_RANK7_7',
        key: '',
        mainType: 'BTM_RANK_7',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '8',
        mutil: 'MT_RANK7_8',
        key: '',
        mainType: 'BTM_RANK_7',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '9',
        mutil: 'MT_RANK7_9',
        key: '',
        mainType: 'BTM_RANK_7',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '10',
        mutil: 'MT_RANK7_10',
        key: '',
        mainType: 'BTM_RANK_7',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      ///第八名
      {
        text: '1',
        mutil: 'MT_RANK8_1',
        key: '',
        mainType: 'BTM_RANK_8',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '2',
        mutil: 'MT_RANK8_2',
        key: '',
        mainType: 'BTM_RANK_8',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '3',
        mutil: 'MT_RANK8_3',
        key: '',
        mainType: 'BTM_RANK_8',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '4',
        mutil: 'MT_RANK8_4',
        key: '',
        mainType: 'BTM_RANK_8',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '5',
        mutil: 'MT_RANK8_5',
        key: '',
        mainType: 'BTM_RANK_8',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '6',
        mutil: 'MT_RANK8_6',
        key: '',
        mainType: 'BTM_RANK_8',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '7',
        mutil: 'MT_RANK8_7',
        key: '',
        mainType: 'BTM_RANK_8',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '8',
        mutil: 'MT_RANK8_8',
        key: '',
        mainType: 'BTM_RANK_8',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '9',
        mutil: 'MT_RANK8_9',
        key: '',
        mainType: 'BTM_RANK_8',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '10',
        mutil: 'MT_RANK8_10',
        key: '',
        mainType: 'BTM_RANK_8',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      ///第九名
      {
        text: '1',
        mutil: 'MT_RANK9_1',
        key: '',
        mainType: 'BTM_RANK_9',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '2',
        mutil: 'MT_RANK9_2',
        key: '',
        mainType: 'BTM_RANK_9',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '3',
        mutil: 'MT_RANK9_3',
        key: '',
        mainType: 'BTM_RANK_9',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '4',
        mutil: 'MT_RANK9_4',
        key: '',
        mainType: 'BTM_RANK_9',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '5',
        mutil: 'MT_RANK9_5',
        key: '',
        mainType: 'BTM_RANK_9',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '6',
        mutil: 'MT_RANK9_6',
        key: '',
        mainType: 'BTM_RANK_9',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '7',
        mutil: 'MT_RANK9_7',
        key: '',
        mainType: 'BTM_RANK_9',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '8',
        mutil: 'MT_RANK9_8',
        key: '',
        mainType: 'BTM_RANK_9',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '9',
        mutil: 'MT_RANK9_9',
        key: '',
        mainType: 'BTM_RANK_9',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '10',
        mutil: 'MT_RANK9_10',
        key: '',
        mainType: 'BTM_RANK_9',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      ///第十名
      {
        text: '1',
        mutil: 'MT_RANK10_1',
        key: '',
        mainType: 'BTM_RANK_10',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '2',
        mutil: 'MT_RANK10_2',
        key: '',
        mainType: 'BTM_RANK_10',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '3',
        mutil: 'MT_RANK10_3',
        key: '',
        mainType: 'BTM_RANK_10',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '4',
        mutil: 'MT_RANK10_4',
        key: '',
        mainType: 'BTM_RANK_10',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '5',
        mutil: 'MT_RANK10_5',
        key: '',
        mainType: 'BTM_RANK_10',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '6',
        mutil: 'MT_RANK10_6',
        key: '',
        mainType: 'BTM_RANK_10',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '7',
        mutil: 'MT_RANK10_7',
        key: '',
        mainType: 'BTM_RANK_10',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '8',
        mutil: 'MT_RANK10_8',
        key: '',
        mainType: 'BTM_RANK_10',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '9',
        mutil: 'MT_RANK10_9',
        key: '',
        mainType: 'BTM_RANK_10',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '10',
        mutil: 'MT_RANK10_10',
        key: '',
        mainType: 'BTM_RANK_10',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
    ],
  },
  {
    title: 'LIANG_MIAN_PAN',
    paneKey: '2',
    list: [
      {
        text: 'GUAN_YA_DA',
        mutil: 'MT_SUM_DA',
        key: '',
        mainType: 'BTM_SUM',
        subMainType: 'SBTS_DA',
        topType: 'none',
        subTypeName: CMD_3102.emBetSubTypeNames[1],
        cls: styels['t-nomal'],
      },
      {
        text: 'GUAN_YA_XIAO',
        mutil: 'MT_SUM_XIAO',
        key: '',
        mainType: 'BTM_SUM',
        subMainType: 'SBTS_XIAO',
        topType: 'none',
        subTypeName: CMD_3102.emBetSubTypeNames[1],
        cls: styels['t-nomal'],
      },
      {
        text: 'GUAN_YA_DAN',
        mutil: 'MT_SUM_DAN',
        key: '',
        mainType: 'BTM_SUM',
        subMainType: 'SBTS_DAN',
        topType: 'none',
        subTypeName: CMD_3102.emBetSubTypeNames[1],
        cls: styels['t-nomal'],
      },
      {
        text: 'GUAN_YA_SHUANG',
        mutil: 'MT_SUM_SHUANG',
        key: '',
        mainType: 'BTM_SUM',
        subMainType: 'SBTS_SHUANG',
        topType: 'none',
        subTypeName: CMD_3102.emBetSubTypeNames[1],
        cls: styels['t-nomal'],
      },
      ///冠军大小单双龙虎
      ...lmSixCom,
      ///第六名大小单双
      ...lmFourCom,
    ]
  },
  {
    title: 'GUAN_YA_HE',
    paneKey: '3',
    list: [
      {
        text: 'GUAN_YA_DA',
        mutil: 'MT_SUM_DA',
        key: '',
        mainType: 'BTM_SUM',
        subMainType: 'SBTS_DA',
        topType: 'none',
        subTypeName: CMD_3102.emBetSubTypeNames[1],
        cls: styels['t-nomal'],
      },
      {
        text: 'GUAN_YA_XIAO',
        mutil: 'MT_SUM_XIAO',
        key: '',
        mainType: 'BTM_SUM',
        subMainType: 'SBTS_XIAO',
        topType: 'none',
        subTypeName: CMD_3102.emBetSubTypeNames[1],
        cls: styels['t-nomal'],
      },
      {
        text: 'GUAN_YA_DAN',
        mutil: 'MT_SUM_DAN',
        key: '',
        mainType: 'BTM_SUM',
        subMainType: 'SBTS_DAN',
        topType: 'none',
        subTypeName: CMD_3102.emBetSubTypeNames[1],
        cls: styels['t-nomal'],
      },
      {
        text: 'GUAN_YA_SHUANG',
        mutil: 'MT_SUM_SHUANG',
        key: '',
        mainType: 'BTM_SUM',
        subMainType: 'SBTS_SHUANG',
        topType: 'none',
        subTypeName: CMD_3102.emBetSubTypeNames[1],
        cls: styels['t-nomal'],
      },
      {
        text: '3',
        mutil: 'MT_SUM_3',
        key: '',
        mainType: 'BTM_SUM',
        subMainType: 'SBTS_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[1],
        cls: styels['t-nomal'],
      },
      {
        text: '4',
        mutil: 'MT_SUM_4',
        key: '',
        mainType: 'BTM_SUM',
        subMainType: 'SBTS_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[1],
        cls: styels['t-nomal'],
      },
      {
        text: '5',
        mutil: 'MT_SUM_5',
        key: '',
        mainType: 'BTM_SUM',
        subMainType: 'SBTS_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[1],
        cls: styels['t-nomal'],
      },
      {
        text: '6',
        mutil: 'MT_SUM_6',
        key: '',
        mainType: 'BTM_SUM',
        subMainType: 'SBTS_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[1],
        cls: styels['t-nomal'],
      },
      {
        text: '7',
        mutil: 'MT_SUM_7',
        key: '',
        mainType: 'BTM_SUM',
        subMainType: 'SBTS_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[1],
        cls: styels['t-nomal'],
      },
      {
        text: '8',
        mutil: 'MT_SUM_8',
        key: '',
        mainType: 'BTM_SUM',
        subMainType: 'SBTS_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[1],
        cls: styels['t-nomal'],
      },
      {
        text: '9',
        mutil: 'MT_SUM_9',
        key: '',
        mainType: 'BTM_SUM',
        subMainType: 'SBTS_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[1],
        cls: styels['t-nomal'],
      },
      {
        text: '10',
        mutil: 'MT_SUM_10',
        key: '',
        mainType: 'BTM_SUM',
        subMainType: 'SBTS_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[1],
        cls: styels['t-nomal'],
      },
      {
        text: '11',
        mutil: 'MT_SUM_11',
        key: '',
        mainType: 'BTM_SUM',
        subMainType: 'SBTS_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[1],
        cls: styels['t-nomal'],
      },
      {
        text: '12',
        mutil: 'MT_SUM_12',
        key: '',
        mainType: 'BTM_SUM',
        subMainType: 'SBTS_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[1],
        cls: styels['t-nomal'],
      },
      {
        text: '13',
        mutil: 'MT_SUM_13',
        key: '',
        mainType: 'BTM_SUM',
        subMainType: 'SBTS_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[1],
        cls: styels['t-nomal'],
      },
      {
        text: '14',
        mutil: 'MT_SUM_14',
        key: '',
        mainType: 'BTM_SUM',
        subMainType: 'SBTS_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[1],
        cls: styels['t-nomal'],
      },
      {
        text: '15',
        mutil: 'MT_SUM_15',
        key: '',
        mainType: 'BTM_SUM',
        subMainType: 'SBTS_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[1],
        cls: styels['t-nomal'],
      },
      {
        text: '16',
        mutil: 'MT_SUM_16',
        key: '',
        mainType: 'BTM_SUM',
        subMainType: 'SBTS_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[1],
        cls: styels['t-nomal'],
      },
      {
        text: '17',
        mutil: 'MT_SUM_17',
        key: '',
        mainType: 'BTM_SUM',
        subMainType: 'SBTS_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[1],
        cls: styels['t-nomal'],
      },
      {
        text: '18',
        mutil: 'MT_SUM_18',
        key: '',
        mainType: 'BTM_SUM',
        subMainType: 'SBTS_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[1],
        cls: styels['t-nomal'],
      },
      {
        text: '19',
        mutil: 'MT_SUM_19',
        key: '',
        mainType: 'BTM_SUM',
        subMainType: 'SBTS_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[1],
        cls: styels['t-nomal'],
      },
      ///冠军大小单双龙虎 1-10
      ...lmSixCom,
      {
        text: '1',
        mutil: 'MT_RANK1_1',
        key: '',
        mainType: 'BTM_RANK_1',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '2',
        mutil: 'MT_RANK1_2',
        key: '',
        mainType: 'BTM_RANK_1',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '3',
        mutil: 'MT_RANK1_3',
        key: '',
        mainType: 'BTM_RANK_1',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '4',
        mutil: 'MT_RANK1_4',
        key: '',
        mainType: 'BTM_RANK_1',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '5',
        mutil: 'MT_RANK1_5',
        key: '',
        mainType: 'BTM_RANK_1',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '6',
        mutil: 'MT_RANK1_6',
        key: '',
        mainType: 'BTM_RANK_1',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '7',
        mutil: 'MT_RANK1_7',
        key: '',
        mainType: 'BTM_RANK_1',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '8',
        mutil: 'MT_RANK1_8',
        key: '',
        mainType: 'BTM_RANK_1',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '9',
        mutil: 'MT_RANK1_9',
        key: '',
        mainType: 'BTM_RANK_1',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '10',
        mutil: 'MT_RANK1_10',
        key: '',
        mainType: 'BTM_RANK_1',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      ///亚军大小单双龙虎 1-10
      ...getLmSixTitle('BTM_RANK_2'),
      {
        text: '1',
        mutil: 'MT_RANK2_1',
        key: '',
        mainType: 'BTM_RANK_2',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '2',
        mutil: 'MT_RANK2_2',
        key: '',
        mainType: 'BTM_RANK_2',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '3',
        mutil: 'MT_RANK2_3',
        key: '',
        mainType: 'BTM_RANK_2',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '4',
        mutil: 'MT_RANK2_4',
        key: '',
        mainType: 'BTM_RANK_2',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '5',
        mutil: 'MT_RANK2_5',
        key: '',
        mainType: 'BTM_RANK_2',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '6',
        mutil: 'MT_RANK2_6',
        key: '',
        mainType: 'BTM_RANK_2',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '7',
        mutil: 'MT_RANK2_7',
        key: '',
        mainType: 'BTM_RANK_2',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '8',
        mutil: 'MT_RANK2_8',
        key: '',
        mainType: 'BTM_RANK_2',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '9',
        mutil: 'MT_RANK2_9',
        key: '',
        mainType: 'BTM_RANK_2',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
      {
        text: '10',
        mutil: 'MT_RANK2_10',
        key: '',
        mainType: 'BTM_RANK_2',
        subMainType: 'SBTR_NUM',
        subTypeName: CMD_3102.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
      },
    ],
  },
  {
    title: 'GUAN_YA_ZUHE',
    paneKey: '4',
    list: [...new Array(10).keys()]
      .map((r1) => {
        const arr = [...new Array(9 - r1).keys()];
        return arr.map((r2) => {
          const text = `${r1 + 1}-${r2 + 1 + r1 + 1}`;
          const mainType = 'BTM_COM';
          const subMainType = 'SBTC_NUM';
          const mutil = 'MT_COM_ALL';
          const subTypeName = CMD_3102.emBetSubTypeNames[2];
          const topType = 'none';
          return {
            text, mutil, mainType, subMainType, subTypeName, topType, key: '', cls: ''
          };
        });
      })
      .flat()
  }
];
