import { CMD_3402 } from '@/engine/game/pc/3402/CMD_3402';
import styels from '../index.module.scss';

// 定义49个号码球
const fourtyNineNums = Array.from({ length: 49 }, (_, index) => {
  if (index < 9) { 
    return `0${index + 1}`;
  } 
    return index + 1;
});

const tou0 = fourtyNineNums.filter((item) => String(item).startsWith('0'));
const tou1 = fourtyNineNums.filter((item) => String(item).startsWith('1'));
const tou2 = fourtyNineNums.filter((item) => String(item).startsWith('2'));
const tou3 = fourtyNineNums.filter((item) => String(item).startsWith('3'));
const tou4 = fourtyNineNums.filter((item) => String(item).startsWith('4'));
const wei0 = fourtyNineNums.filter((item) => String(item).endsWith('0'));
const wei1 = fourtyNineNums.filter((item) => String(item).endsWith('1'));
const wei2 = fourtyNineNums.filter((item) => String(item).endsWith('2'));
const wei3 = fourtyNineNums.filter((item) => String(item).endsWith('3'));
const wei4 = fourtyNineNums.filter((item) => String(item).endsWith('4'));
const wei5 = fourtyNineNums.filter((item) => String(item).endsWith('5'));
const wei6 = fourtyNineNums.filter((item) => String(item).endsWith('6'));
const wei7 = fourtyNineNums.filter((item) => String(item).endsWith('7'));
const wei8 = fourtyNineNums.filter((item) => String(item).endsWith('8'));
const wei9 = fourtyNineNums.filter((item) => String(item).endsWith('9'));

// 头尾数
export const touWeiArr = [tou0, tou1, tou2, tou3, tou4, wei0, wei1, wei2, wei3, wei4, wei5, wei6, wei7, wei8, wei9];

// 尾数
export const weiArr = [wei0, wei1, wei2, wei3, wei4, wei5, wei6, wei7, wei8, wei9];

// 连尾
export const lwArr = ['0尾', '1尾', '2尾', '3尾', '4尾', '5尾', '6尾', '7尾', '8尾', '9尾'];

const jin = [1, 2, 9, 10, 23, 24, 31, 32, 39, 40];
const mu = [5, 6, 13, 14, 21, 22, 35, 36, 43, 44];
const shui = [11, 12, 19, 29, 27, 28, 41, 42, 49];
const huo = [7, 8, 15, 16, 29, 30, 37, 38, 45, 46];
const tu = [3, 4, 17, 18, 25, 26, 33, 34, 47, 48];
// 五行
export const wuHangArr = [jin, mu, shui, huo, tu];
// 色波
const redBo = [1, 2, 7, 8, 12, 13, 18, 19, 23, 24, 29, 30, 34, 35, 40, 45, 46];
const blueBo = [3, 4, 9, 10, 14, 15, 20, 25, 26, 31, 36, 37, 41, 42, 47, 48];
const greenBo = [5, 6, 11, 16, 17, 21, 22, 27, 28, 32, 33, 38, 39, 43, 44, 49];
//半波
const redSingle = [1, 7, 13, 19, 23, 29, 35, 45];
const redDouble = [2, 8, 12, 18, 24, 30, 34, 40, 46];
const redBig = [29, 30, 34, 35, 40, 45, 46];
const redSmall = [1, 2, 7, 8, 12, 13, 18, 19, 23, 24];
const blueSingle = [3, 9, 15, 25, 31, 37, 41, 47];
const blueDouble = [4, 10, 14, 20, 26, 36, 42, 48];
const blueBig = [25, 26, 31, 36, 37, 41, 42, 47, 48];
const blueSmall = [3, 4, 9, 10, 14, 15, 20];
const greenSingle = [5, 11, 17, 21, 27, 33, 39, 43, 49];
const greenDouble = [6, 16, 22, 28, 32, 38, 44];
const greenBig = [27, 28, 32, 33, 38, 39, 43, 44, 49];
const greenSmall = [5, 6, 11, 16, 17, 21, 22];
// 半半波
const redBigSig = [29, 35, 45];
const redBigDou = [30, 34, 40, 46];
const redSmallSig = [1, 7, 13, 19, 23];
const redSmallDou = [2, 8, 12, 18, 24];
const blueBigSig = [25, 31, 37, 41, 47];
const blueBigDou = [26, 36, 42, 48];
const blueSmallSig = [3, 9, 15];
const blueSmallDou = [4, 10, 14, 20];
const greenBigSig = [27, 33, 39, 43, 49];
const greenBigDou = [28, 32, 38, 44];
const greenSmallSig = [5, 11, 17, 21];
const greenSmallDou = [6, 16, 22];

// 色波
export const seBo = [redBo, blueBo, greenBo];
// 半波
export const banBo = [redSingle, redDouble, redBig, redSmall, blueSingle, blueDouble, blueBig, blueSmall, greenSingle, greenDouble, greenBig, greenSmall];
// 半半波
export const banbanBo = [redBigSig, redBigDou, redSmallSig, redSmallDou, blueBigSig, blueBigDou, blueSmallSig, blueSmallDou, greenBigSig, greenBigDou, greenSmallSig, greenSmallDou];


// 1-49 号码配置
const numList = [];
fourtyNineNums.forEach((item) => {
  numList.push({
    text: `${item}`,
    mutil: 'MT_TE_NUM',
    key: '',
    mainType: 'BTM_TE',
    subMainType: 'SBTT_NUM',
    subTypeName: CMD_3402.emBetSubTypeNames[0],
    cls: styels['t-nomal'],
    // topType: 'none',
  });
});

// 3402 content 按钮快 ：展示常量
export const tabListFirst = [
  {
    title: '特码',
    key: '0',
    listKey: 'tmArr',
  },
  {
    title: '正码',
    key: '1',
    listKey: 'tmArr',
  },
  {
    title: '正一特',
    key: '2',
    listKey: 'tmArr',
  },
  {
    title: '正二特',
    key: '3',
    listKey: 'tmArr',
  },
  {
    title: '正三特',
    key: '4',
    listKey: 'tmArr',
  },

  {
    title: '正四特',
    key: '5',
    listKey: 'tmArr',
  },
  {
    title: '正五特',
    key: '6',
    listKey: 'tmArr',
  },
  {
    title: '正六特',
    key: '7',
    listKey: 'tmArr',
  },
  {
    title: '两面',
    key: '8',
    listKey: 'lmArr',
  },
  [{
    title: '正码一',
    key: '9',
    listKey: 'zmOneArr',
  },
  {
    title: '正码二',
    key: '9',
    listKey: 'zmTwoArr',
  },
  {
    title: '正码三',
    key: '9',
    listKey: 'zmThreeArr',
  },
  {
    title: '正码四',
    key: '9',
    listKey: 'zmFourArr',
  },
  {
    title: '正码五',
    key: '9',
    listKey: 'zmFiveArr',
  },
  {
    title: '正码六',
    key: '9',
    listKey: 'zmSixArr',
    }],
  {
    title: '总肖',
    key: '10',
    listKey: 'zxArr',
  },
  {
    title: '特肖',
    key: '11',
    listKey: 'txArr',
  },
  {
    title: '正肖',
    key: '12',
    listKey: 'zhxArr',
  },
  {
    title: '一肖',
    key: '13',
    listKey: 'yxArr',
  },
  {
    title: '连肖',
    key: '14',
    listKey: 'lxArr',
  },
  {
    title: '合肖',
    key: '15',
    listKey: 'hxArr',
  },
  {
    title: '头尾数',
    key: '16',
    listKey: 'twsArr',
  },
  {
    title: '五行',
    key: '17',
    listKey: 'whArr',
  },
  {
    title: '尾数',
    key: '18',
    listKey: 'wsArr',
  },
  {
    title: '连尾',
    key: '19',
    listKey: 'lwArr',
  },
  {
    title: '连码',
    key: '20',
    listKey: 'lmaArr',
  },
  {
    title: '全不中',
    key: '21',
    listKey: 'qbzArr',
  },
  {
    title: '色波',
    key: '22',
    listKey: 'sbArr',
  },

];


// 正码1 与其他正码 就主码不一样;
const zmOneList = [
  {
    text: '大',
    mutil: 'MT_ZN_DA',
    key: '',
    mainType: 'BTM_ZHENG_1',
    subMainType: 'SBTZN_DA',
    subTypeName: CMD_3402.emBetSubTypeNames[1],
    cls: styels['t-nomal'],
    topType: 'none',
  },
  {
    text: '小',
    mutil: 'MT_ZN_XIAO',
    key: '',
    mainType: 'BTM_ZHENG_1',
    subMainType: 'SBTZN_XIAO',
    subTypeName: CMD_3402.emBetSubTypeNames[1],
    cls: styels['t-nomal'],
    topType: 'none',
  },
  {
    text: '单',
    mutil: 'MT_ZN_DAN',
    key: '',
    mainType: 'BTM_ZHENG_1',
    subMainType: 'SBTZN_DAN',
    subTypeName: CMD_3402.emBetSubTypeNames[1],
    cls: styels['t-nomal'],
    topType: 'none',
  },
  {
    text: '双',
    mutil: 'MT_ZN_SHUANG',
    key: '',
    mainType: 'BTM_ZHENG_1',
    subMainType: 'SBTZN_SHUANG',
    subTypeName: CMD_3402.emBetSubTypeNames[1],
    cls: styels['t-nomal'],
    topType: 'none',
  },
  {
    text: '合大',
    mutil: 'MT_ZN_HE_DA',
    key: '',
    mainType: 'BTM_ZHENG_1',
    subMainType: 'SBTZN_HE_DA',
    subTypeName: CMD_3402.emBetSubTypeNames[1],
    cls: styels['t-nomal'],
    topType: 'none',
  },
  {
    text: '合小',
    mutil: 'MT_ZN_HE_XIAO',
    key: '',
    mainType: 'BTM_ZHENG_1',
    subMainType: 'SBTZN_HE_XIAO',
    subTypeName: CMD_3402.emBetSubTypeNames[1],
    cls: styels['t-nomal'],
    topType: 'none',
  },
 
  {
    text: '合单',
    mutil: 'MT_ZN_HE_DAN',
    key: '',
    mainType: 'BTM_ZHENG_1',
    subMainType: 'SBTZN_HE_DAN',
    subTypeName: CMD_3402.emBetSubTypeNames[1],
    cls: styels['t-nomal'],
    topType: 'none',
  },
  {
    text: '合双',
    mutil: 'MT_ZN_HE_SHUANG',
    key: '',
    mainType: 'BTM_ZHENG_1',
    subMainType: 'SBTZN_HE_SHUANG',
    subTypeName: CMD_3402.emBetSubTypeNames[1],
    cls: styels['t-nomal'],
    topType: 'none',
  },
  {
    text: '尾大',
    mutil: 'MT_ZN_WEI_DA',
    key: '',
    mainType: 'BTM_ZHENG_1',
    subMainType: 'SBTZN_WEI_DA',
    subTypeName: CMD_3402.emBetSubTypeNames[1],
    cls: styels['t-nomal'],
    topType: 'none',
  },
  {
    text: '尾小',
    mutil: 'MT_ZN_WEI_XIAO',
    key: '',
    mainType: 'BTM_ZHENG_1',
    subMainType: 'SBTZN_WEI_XIAO',
    subTypeName: CMD_3402.emBetSubTypeNames[1],
    cls: styels['t-nomal'],
    topType: 'none',
  },
  {
    text: '红波',
    mutil: 'MT_ZN_HONG',
    key: '',
    mainType: 'BTM_ZHENG_1',
    subMainType: 'SBTZN_HONG',
    subTypeName: CMD_3402.emBetSubTypeNames[1],
    cls: styels['t-nomal'],
    topType: 'none',
  },
  {
    text: '蓝波',
    mutil: 'MT_ZN_LAN',
    key: '',
    mainType: 'BTM_ZHENG_1',
    subMainType: 'SBTZN_LAN',
    subTypeName: CMD_3402.emBetSubTypeNames[1],
    cls: styels['t-nomal'],
    topType: 'none',
  },
  {
    text: '绿波',
    mutil: 'MT_ZN_LV',
    key: '',
    mainType: 'BTM_ZHENG_1',
    subMainType: 'SBTZN_LV',
    subTypeName: CMD_3402.emBetSubTypeNames[1],
    cls: styels['t-nomal'],
    topType: 'none',
  },
];

// 正码2
const zmTwoList = zmOneList.map((item) => {
  const newItem = { ...item, mainType: 'BTM_ZHENG_2' };
  return newItem;
});
// 正码3
const zmThreeList = zmOneList.map((item) => {
  const newItem = { ...item, mainType: 'BTM_ZHENG_3' };
  return newItem;
});
// 正码4
const zmFourList = zmOneList.map((item) => {
  const newItem = { ...item, mainType: 'BTM_ZHENG_4' };
  return newItem;
});
// 正码5
const zmFiveList = zmOneList.map((item) => {
  const newItem = { ...item, mainType: 'BTM_ZHENG_5' };
  return newItem;
});
// 正码6
const zmSixList = zmOneList.map((item) => {
  const newItem = { ...item, mainType: 'BTM_ZHENG_6' };
  return newItem;
});

interface ListProps { 
  text: string;
  mutil: string;
  key?: string;
  mainType: string;
  subMainType: string;
  subTypeName: string;
  cls?: any;
  topType?: string;
  child?: any[];
}
interface BetNumberListProps { 
  title: string;
  paneKey: string;
  list:ListProps[]

}

// 3402 content 按钮快 ：展示常量
export const betNumberList: BetNumberListProps[] = [
  {
    title: '特码',
    paneKey: '1',
    list: [
      ...numList
    ]
  },
  {
    title: '两面',
    paneKey: '2',
    list: [
      {
        text: '特大',
        mutil: 'MT_TE_DA',
        key: '',
        mainType: 'BTM_TE',
        subMainType: 'SBTT_DA',
        subTypeName: CMD_3402.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '特小',
        mutil: 'MT_TE_XIAO',
        key: '',
        mainType: 'BTM_TE',
        subMainType: 'SBTT_XIAO',
        subTypeName: CMD_3402.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '特单',
        mutil: 'MT_TE_DAN',
        key: '',
        mainType: 'BTM_TE',
        subMainType: 'SBTT_DAN',
        subTypeName: CMD_3402.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '特双',
        mutil: 'MT_TE_SHUANG',
        key: '',
        mainType: 'BTM_TE',
        subMainType: 'SBTT_SHUANG',
        subTypeName: CMD_3402.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '特大单',
        mutil: 'MT_TE_DA_DAN',
        key: '',
        mainType: 'BTM_TE',
        subMainType: 'SBTT_DA_DAN',
        subTypeName: CMD_3402.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '特小单',
        mutil: 'MT_TE_XIAO_DAN',
        key: '',
        mainType: 'BTM_TE',
        subMainType: 'SBTT_XIAO_DAN',
        subTypeName: CMD_3402.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '特大双',
        mutil: 'MT_TE_DA_SHUANG',
        key: '',
        mainType: 'BTM_TE',
        subMainType: 'SBTT_DA_SHUANG',
        subTypeName: CMD_3402.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '特小双',
        mutil: 'MT_TE_XIAO_SHUANG',
        key: '',
        mainType: 'BTM_TE',
        subMainType: 'SBTT_XIAO_SHUANG',
        subTypeName: CMD_3402.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '特合大',
        mutil: 'MT_TE_HE_DA',
        key: '',
        mainType: 'BTM_TE',
        subMainType: 'SBTT_HE_DA',
        subTypeName: CMD_3402.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '特合小',
        mutil: 'MT_TE_HE_XIAO',
        key: '',
        mainType: 'BTM_TE',
        subMainType: 'SBTT_HE_XIAO',
        subTypeName: CMD_3402.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
        topType: 'none',
      },
     
      {
        text: '特合单',
        mutil: 'MT_TE_HE_DAN',
        key: '',
        mainType: 'BTM_TE',
        subMainType: 'SBTT_HE_DAN',
        subTypeName: CMD_3402.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '特合双',
        mutil: 'MT_TE_HE_SHUANG',
        key: '',
        mainType: 'BTM_TE',
        subMainType: 'SBTT_HE_SHUANG',
        subTypeName: CMD_3402.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '特尾大',
        mutil: 'MT_TE_WEI_DA',
        key: '',
        mainType: 'BTM_TE',
        subMainType: 'SBTT_WEI_DA',
        subTypeName: CMD_3402.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '特尾小',
        mutil: 'MT_TE_WEI_XIAO',
        key: '',
        mainType: 'BTM_TE',
        subMainType: 'SBTT_WEI_XIAO',
        subTypeName: CMD_3402.emBetSubTypeNames[0],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '特天肖',
        mutil: 'MT_TX_TIAN',
        key: '',
        mainType: 'BTM_XIAO',
        subMainType: 'SBTX_XIAO_TIAN',
        subTypeName: CMD_3402.emBetSubTypeNames[8],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '特地肖',
        mutil: 'MT_TX_DI',
        key: '',
        mainType: 'BTM_XIAO',
        subMainType: 'SBTX_XIAO_DI',
        subTypeName: CMD_3402.emBetSubTypeNames[8],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '特前肖',
        mutil: 'MT_TX_QIAN',
        key: '',
        mainType: 'BTM_XIAO',
        subMainType: 'SBTX_XIAO_QIAN',
        subTypeName: CMD_3402.emBetSubTypeNames[8],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '特后肖',
        mutil: 'MT_TX_HOU',
        key: '',
        mainType: 'BTM_XIAO',
        subMainType: 'SBTX_XIAO_HOU',
        subTypeName: CMD_3402.emBetSubTypeNames[8],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '特家肖',
        mutil: 'MT_TX_JIA',
        key: '',
        mainType: 'BTM_XIAO',
        subMainType: 'SBTX_XIAO_JIA',
        subTypeName: CMD_3402.emBetSubTypeNames[8],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '特野肖',
        mutil: 'MT_TX_YE',
        key: '',
        mainType: 'BTM_XIAO',
        subMainType: 'SBTX_XIAO_YE',
        subTypeName: CMD_3402.emBetSubTypeNames[8],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '总大',
        mutil: 'MT_HE_DA',
        key: '',
        mainType: 'BTM_HE',
        subMainType: 'SBTH_DA',
        subTypeName: CMD_3402.emBetSubTypeNames[3],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '总小',
        mutil: 'MT_HE_XIAO',
        key: '',
        mainType: 'BTM_HE',
        subMainType: 'SBTH_XIAO',
        subTypeName: CMD_3402.emBetSubTypeNames[3],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '总单',
        mutil: 'MT_HE_DAN',
        key: '',
        mainType: 'BTM_HE',
        subMainType: 'SBTH_DAN',
        subTypeName: CMD_3402.emBetSubTypeNames[3],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '总双',
        mutil: 'MT_HE_SHUANG',
        key: '',
        mainType: 'BTM_HE',
        subMainType: 'SBTH_SHUANG',
        subTypeName: CMD_3402.emBetSubTypeNames[3],
        cls: styels['t-nomal'],
        topType: 'none',
      },
    ]
  },
  {
    title: '正码1',
    paneKey: '3',
    list: zmOneList,
  },
  {
    title: '正码2',
    paneKey: '4',
    list: zmTwoList
  },
  {
    title: '正码3',
    paneKey: '5',
    list: zmThreeList
  },
  {
    title: '正码4',
    paneKey: '6',
    list: zmFourList
  },
  {
    title: '正码5',
    paneKey: '7',
    list: zmFiveList
  },
  {
    title: '正码6',
    paneKey: '8',
    list: zmSixList
  },
  {
    title: '总肖',
    paneKey: '9',
    list: [
      {
        text: '2肖',
        mutil: 'MT_ZX_SHU_2',
        key: '',
        mainType: 'BTM_ZONG_XIAO',
        subMainType: 'SBTZX_SHU',
        subTypeName: CMD_3402.emBetSubTypeNames[9],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '3肖',
        mutil: 'MT_ZX_SHU_3',
        key: '',
        mainType: 'BTM_ZONG_XIAO',
        subMainType: 'SBTZX_SHU',
        subTypeName: CMD_3402.emBetSubTypeNames[9],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '4肖',
        mutil: 'MT_ZX_SHU_4',
        key: '',
        mainType: 'BTM_ZONG_XIAO',
        subMainType: 'SBTZX_SHU',
        subTypeName: CMD_3402.emBetSubTypeNames[9],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '5肖',
        mutil: 'MT_ZX_SHU_5',
        key: '',
        mainType: 'BTM_ZONG_XIAO',
        subMainType: 'SBTZX_SHU',
        subTypeName: CMD_3402.emBetSubTypeNames[9],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '6肖',
        mutil: 'MT_ZX_SHU_6',
        key: '',
        mainType: 'BTM_ZONG_XIAO',
        subMainType: 'SBTZX_SHU',
        subTypeName: CMD_3402.emBetSubTypeNames[9],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '7肖',
        mutil: 'MT_ZX_SHU_7',
        key: '',
        mainType: 'BTM_ZONG_XIAO',
        subMainType: 'SBTZX_SHU',
        subTypeName: CMD_3402.emBetSubTypeNames[9],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '总肖单',
        mutil: 'MT_ZX_DAN',
        key: '',
        mainType: 'BTM_ZONG_XIAO',
        subMainType: 'SBTZX_DAN',
        subTypeName: CMD_3402.emBetSubTypeNames[9],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '总肖双',
        mutil: 'MT_ZX_SHUANG',
        key: '',
        mainType: 'BTM_ZONG_XIAO',
        subMainType: 'SBTZX_SHUANG',
        subTypeName: CMD_3402.emBetSubTypeNames[9],
        cls: styels['t-nomal'],
        topType: 'none',
      },
    ],
  },
  {
    title: '特肖',
    paneKey: '10',
    list: [
      {
        text: '特肖自选',
        mutil: 'MT_TX',
        key: '',
        mainType: 'BTM_XIAO',
        subMainType: 'SBTX_TE',
        subTypeName: CMD_3402.emBetSubTypeNames[8],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '特肖本年',
        mutil: 'MT_TX_BEN',
        key: '',
        mainType: 'BTM_XIAO',
        subMainType: 'SBTX_TE_BEN',
        subTypeName: CMD_3402.emBetSubTypeNames[8],
        cls: styels['t-nomal'],
        topType: 'none',
      },
    ]
  },
  {
    title: '正肖',
    paneKey: '11',
    list: [
      {
        text: '正肖自选',
        mutil: 'MT_ZX',
        key: '',
        mainType: 'BTM_XIAO',
        subMainType: 'SBTX_ZHENG',
        subTypeName: CMD_3402.emBetSubTypeNames[8],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '正肖本年',
        mutil: 'MT_ZX_BEN',
        key: '',
        mainType: 'BTM_XIAO',
        subMainType: 'SBTX_ZHENG_BEN',
        subTypeName: CMD_3402.emBetSubTypeNames[8],
        cls: styels['t-nomal'],
        topType: 'none',
      },
    ]
  },
  {
    title: '一肖',
    paneKey: '12',
    list: [
      {
        text: '一肖自选',
        mutil: 'MT_YX',
        key: '',
        mainType: 'BTM_XIAO',
        subMainType: 'SBTX_YI',
        subTypeName: CMD_3402.emBetSubTypeNames[8],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '一肖本年',
        mutil: 'MT_YX_BEN',
        key: '',
        mainType: 'BTM_XIAO',
        subMainType: 'SBTX_YI_BEN',
        subTypeName: CMD_3402.emBetSubTypeNames[8],
        cls: styels['t-nomal'],
        topType: 'none',
      },
    ]
  },
  {
    title: '连肖',
    paneKey: '13',
    list: [
      {
        text: '二连肖',
        mutil: 'MT_SXL_ZHONG_2',
        key: '',
        mainType: 'BTM_SHENG_XIAO_LIAN',
        subMainType: 'SBTSXL_ZHONG_2',
        subTypeName: CMD_3402.emBetSubTypeNames[11],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '三连肖',
        mutil: 'MT_SXL_ZHONG_3',
        key: '',
        mainType: 'BTM_SHENG_XIAO_LIAN',
        subMainType: 'SBTSXL_ZHONG_3',
        subTypeName: CMD_3402.emBetSubTypeNames[11],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '四连肖',
        mutil: 'MT_SXL_ZHONG_4',
        key: '',
        mainType: 'BTM_SHENG_XIAO_LIAN',
        subMainType: 'SBTSXL_ZHONG_4',
        subTypeName: CMD_3402.emBetSubTypeNames[11],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '五连肖',
        mutil: 'MT_SXL_ZHONG_5',
        key: '',
        mainType: 'BTM_SHENG_XIAO_LIAN',
        subMainType: 'SBTSXL_ZHONG_5',
        subTypeName: CMD_3402.emBetSubTypeNames[11],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '二连肖本年',
        mutil: 'MT_SXL_ZHONG_2_BEN',
        key: '',
        mainType: 'BTM_SHENG_XIAO_LIAN',
        subMainType: 'SBTSXL_ZHONG_2_BEN',
        subTypeName: CMD_3402.emBetSubTypeNames[11],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '三连肖本年',
        mutil: 'MT_SXL_ZHONG_3_BEN',
        key: '',
        mainType: 'BTM_SHENG_XIAO_LIAN',
        subMainType: 'SBTSXL_ZHONG_3_BEN',
        subTypeName: CMD_3402.emBetSubTypeNames[11],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '四连肖本年',
        mutil: 'MT_SXL_ZHONG_4_BEN',
        key: '',
        mainType: 'BTM_SHENG_XIAO_LIAN',
        subMainType: 'SBTSXL_ZHONG_4_BEN',
        subTypeName: CMD_3402.emBetSubTypeNames[11],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '五连肖本年',
        mutil: 'MT_SXL_ZHONG_5_BEN',
        key: '',
        mainType: 'BTM_SHENG_XIAO_LIAN',
        subMainType: 'SBTSXL_ZHONG_5_BEN',
        subTypeName: CMD_3402.emBetSubTypeNames[11],
        cls: styels['t-nomal'],
        topType: 'none',
      },
    ]
  },
  {
    title: '合肖',
    paneKey: '14',
    list: [
      {
        text: '二合肖',
        mutil: 'MT_HE_ZHONG_2',
        key: '',
        mainType: 'BTM_HE_XIAO',
        subMainType: 'SBTHX_ZHONG_2',
        subTypeName: CMD_3402.emBetSubTypeNames[10],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '三合肖',
        mutil: 'MT_HE_ZHONG_3',
        key: '',
        mainType: 'BTM_HE_XIAO',
        subMainType: 'SBTHX_ZHONG_3',
        subTypeName: CMD_3402.emBetSubTypeNames[10],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '四合肖',
        mutil: 'MT_HE_ZHONG_4',
        key: '',
        mainType: 'BTM_HE_XIAO',
        subMainType: 'SBTHX_ZHONG_4',
        subTypeName: CMD_3402.emBetSubTypeNames[10],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '五合肖',
        mutil: 'MT_HE_ZHONG_5',
        key: '',
        mainType: 'BTM_HE_XIAO',
        subMainType: 'SBTHX_ZHONG_5',
        subTypeName: CMD_3402.emBetSubTypeNames[10],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '六合肖',
        mutil: 'MT_HE_ZHONG_6',
        key: '',
        mainType: 'BTM_HE_XIAO',
        subMainType: 'SBTHX_ZHONG_6',
        subTypeName: CMD_3402.emBetSubTypeNames[10],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '七合肖',
        mutil: 'MT_HE_ZHONG_7',
        key: '',
        mainType: 'BTM_HE_XIAO',
        subMainType: 'SBTHX_ZHONG_7',
        subTypeName: CMD_3402.emBetSubTypeNames[10],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '八合肖',
        mutil: 'MT_HE_ZHONG_8',
        key: '',
        mainType: 'BTM_HE_XIAO',
        subMainType: 'SBTHX_ZHONG_8',
        subTypeName: CMD_3402.emBetSubTypeNames[10],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '九合肖',
        mutil: 'MT_HE_ZHONG_9',
        key: '',
        mainType: 'BTM_HE_XIAO',
        subMainType: 'SBTHX_ZHONG_9',
        subTypeName: CMD_3402.emBetSubTypeNames[10],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '十合肖',
        mutil: 'MT_HE_ZHONG_10',
        key: '',
        mainType: 'BTM_HE_XIAO',
        subMainType: 'SBTHX_ZHONG_10',
        subTypeName: CMD_3402.emBetSubTypeNames[10],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '十一合肖',
        mutil: 'MT_HE_ZHONG_11',
        key: '',
        mainType: 'BTM_HE_XIAO',
        subMainType: 'SBTHX_ZHONG_11',
        subTypeName: CMD_3402.emBetSubTypeNames[10],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '二合肖本年',
        mutil: 'MT_HE_ZHONG_2_BEN',
        key: '',
        mainType: 'BTM_HE_XIAO',
        subMainType: 'SBTHX_ZHONG_2_BEN',
        subTypeName: CMD_3402.emBetSubTypeNames[10],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '三合肖本年',
        mutil: 'MT_HE_ZHONG_3_BEN',
        key: '',
        mainType: 'BTM_HE_XIAO',
        subMainType: 'SBTHX_ZHONG_3_BEN',
        subTypeName: CMD_3402.emBetSubTypeNames[10],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '四合肖本年',
        mutil: 'MT_HE_ZHONG_4_BEN',
        key: '',
        mainType: 'BTM_HE_XIAO',
        subMainType: 'SBTHX_ZHONG_4_BEN',
        subTypeName: CMD_3402.emBetSubTypeNames[10],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '五合肖本年',
        mutil: 'MT_HE_ZHONG_5_BEN',
        key: '',
        mainType: 'BTM_HE_XIAO',
        subMainType: 'SBTHX_ZHONG_5_BEN',
        subTypeName: CMD_3402.emBetSubTypeNames[10],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '六合肖本年',
        mutil: 'MT_HE_ZHONG_6_BEN',
        key: '',
        mainType: 'BTM_HE_XIAO',
        subMainType: 'SBTHX_ZHONG_6_BEN',
        subTypeName: CMD_3402.emBetSubTypeNames[10],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '七合肖本年',
        mutil: 'MT_HE_ZHONG_7_BEN',
        key: '',
        mainType: 'BTM_HE_XIAO',
        subMainType: 'SBTHX_ZHONG_7_BEN',
        subTypeName: CMD_3402.emBetSubTypeNames[10],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '八合肖本年',
        mutil: 'MT_HE_ZHONG_8_BEN',
        key: '',
        mainType: 'BTM_HE_XIAO',
        subMainType: 'SBTHX_ZHONG_8_BEN',
        subTypeName: CMD_3402.emBetSubTypeNames[10],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '九合肖本年',
        mutil: 'MT_HE_ZHONG_9_BEN',
        key: '',
        mainType: 'BTM_HE_XIAO',
        subMainType: 'SBTHX_ZHONG_9_BEN',
        subTypeName: CMD_3402.emBetSubTypeNames[10],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '十合肖本年',
        mutil: 'MT_HE_ZHONG_10_BEN',
        key: '',
        mainType: 'BTM_HE_XIAO',
        subMainType: 'SBTHX_ZHONG_10_BEN',
        subTypeName: CMD_3402.emBetSubTypeNames[10],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '十一合肖本年',
        mutil: 'MT_HE_ZHONG_11_BEN',
        key: '',
        mainType: 'BTM_HE_XIAO',
        subMainType: 'SBTHX_ZHONG_11_BEN',
        subTypeName: CMD_3402.emBetSubTypeNames[10],
        cls: styels['t-nomal'],
        topType: 'none',
      },
    ]
  },
  {
    title: '头尾数',
    paneKey: '15',
    list: [
      {
        text: '0头',
        mutil: 'MT_TTW_TOU_0',
        key: '',
        mainType: 'BTM_TE_TOU_WEI',
        subMainType: 'SBTTTW_TOU',
        subTypeName: CMD_3402.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '1头',
        mutil: 'MT_TTW_TOU_1_4',
        key: '',
        mainType: 'BTM_TE_TOU_WEI',
        subMainType: 'SBTTTW_TOU',
        subTypeName: CMD_3402.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '2头',
        mutil: 'MT_TTW_TOU_1_4',
        key: '',
        mainType: 'BTM_TE_TOU_WEI',
        subMainType: 'SBTTTW_TOU',
        subTypeName: CMD_3402.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '3头',
        mutil: 'MT_TTW_TOU_1_4',
        key: '',
        mainType: 'BTM_TE_TOU_WEI',
        subMainType: 'SBTTTW_TOU',
        subTypeName: CMD_3402.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '4头',
        mutil: 'MT_TTW_TOU_1_4',
        key: '',
        mainType: 'BTM_TE_TOU_WEI',
        subMainType: 'SBTTTW_TOU',
        subTypeName: CMD_3402.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '0尾',
        mutil: 'MT_TTW_WEI_0',
        key: '',
        mainType: 'BTM_TE_TOU_WEI',
        subMainType: 'SBTTTW_WEI',
        subTypeName: CMD_3402.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '1尾',
        mutil: 'MT_TTW_WEI_1_9',
        key: '',
        mainType: 'BTM_TE_TOU_WEI',
        subMainType: 'SBTTTW_WEI',
        subTypeName: CMD_3402.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '2尾',
        mutil: 'MT_TTW_WEI_1_9',
        key: '',
        mainType: 'BTM_TE_TOU_WEI',
        subMainType: 'SBTTTW_WEI',
        subTypeName: CMD_3402.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '3尾',
        mutil: 'MT_TTW_WEI_1_9',
        key: '',
        mainType: 'BTM_TE_TOU_WEI',
        subMainType: 'SBTTTW_WEI',
        subTypeName: CMD_3402.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '4尾',
        mutil: 'MT_TTW_WEI_1_9',
        key: '',
        mainType: 'BTM_TE_TOU_WEI',
        subMainType: 'SBTTTW_WEI',
        subTypeName: CMD_3402.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '5尾',
        mutil: 'MT_TTW_WEI_1_9',
        key: '',
        mainType: 'BTM_TE_TOU_WEI',
        subMainType: 'SBTTTW_WEI',
        subTypeName: CMD_3402.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '6尾',
        mutil: 'MT_TTW_WEI_1_9',
        key: '',
        mainType: 'BTM_TE_TOU_WEI',
        subMainType: 'SBTTTW_WEI',
        subTypeName: CMD_3402.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '7尾',
        mutil: 'MT_TTW_WEI_1_9',
        key: '',
        mainType: 'BTM_TE_TOU_WEI',
        subMainType: 'SBTTTW_WEI',
        subTypeName: CMD_3402.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '8尾',
        mutil: 'MT_TTW_WEI_1_9',
        key: '',
        mainType: 'BTM_TE_TOU_WEI',
        subMainType: 'SBTTTW_WEI',
        subTypeName: CMD_3402.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '9尾',
        mutil: 'MT_TTW_WEI_1_9',
        key: '',
        mainType: 'BTM_TE_TOU_WEI',
        subMainType: 'SBTTTW_WEI',
        subTypeName: CMD_3402.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
    ]
  },
  {
    title: '五行',
    paneKey: '16',
    list: [
      {
        text: '金',
        mutil: 'MT_WX_JIN',
        key: '',
        mainType: 'BTM_WU_XING',
        subMainType: 'SBTWX_JIN',
        subTypeName: CMD_3402.emBetSubTypeNames[15],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '木',
        mutil: 'MT_WX_MU',
        key: '',
        mainType: 'BTM_WU_XING',
        subMainType: 'SBTWX_MU',
        subTypeName: CMD_3402.emBetSubTypeNames[15],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '水',
        mutil: 'MT_WX_SHUI',
        key: '',
        mainType: 'BTM_WU_XING',
        subMainType: 'SBTWX_SHUI',
        subTypeName: CMD_3402.emBetSubTypeNames[15],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '火',
        mutil: 'MT_WX_HUO',
        key: '',
        mainType: 'BTM_WU_XING',
        subMainType: 'SBTWX_HUO',
        subTypeName: CMD_3402.emBetSubTypeNames[15],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '土',
        mutil: 'MT_WX_TU',
        key: '',
        mainType: 'BTM_WU_XING',
        subMainType: 'SBTWX_TU',
        subTypeName: CMD_3402.emBetSubTypeNames[15],
        cls: styels['t-nomal'],
        topType: 'none',
      },
    ]
  },
  {
    title: '尾数',
    paneKey: '17',
    list: [
      {
        text: '0尾',
        mutil: 'MT_ZTW_0',
        key: '',
        mainType: 'BTM_ZHENG_TE_WEI',
        subMainType: 'SBTZTW_NUM',
        subTypeName: CMD_3402.emBetSubTypeNames[6],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '1尾',
        mutil: 'MT_ZTW_1_9',
        key: '',
        mainType: 'BTM_ZHENG_TE_WEI',
        subMainType: 'SBTZTW_NUM',
        subTypeName: CMD_3402.emBetSubTypeNames[6],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '2尾',
        mutil: 'MT_ZTW_1_9',
        key: '',
        mainType: 'BTM_ZHENG_TE_WEI',
        subMainType: 'SBTZTW_NUM',
        subTypeName: CMD_3402.emBetSubTypeNames[6],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '3尾',
        mutil: 'MT_ZTW_1_9',
        key: '',
        mainType: 'BTM_ZHENG_TE_WEI',
        subMainType: 'SBTZTW_NUM',
        subTypeName: CMD_3402.emBetSubTypeNames[6],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '4尾',
        mutil: 'MT_ZTW_1_9',
        key: '',
        mainType: 'BTM_ZHENG_TE_WEI',
        subMainType: 'SBTZTW_NUM',
        subTypeName: CMD_3402.emBetSubTypeNames[6],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '5尾',
        mutil: 'MT_ZTW_1_9',
        key: '',
        mainType: 'BTM_ZHENG_TE_WEI',
        subMainType: 'SBTZTW_NUM',
        subTypeName: CMD_3402.emBetSubTypeNames[6],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '6尾',
        mutil: 'MT_ZTW_1_9',
        key: '',
        mainType: 'BTM_ZHENG_TE_WEI',
        subMainType: 'SBTZTW_NUM',
        subTypeName: CMD_3402.emBetSubTypeNames[6],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '7尾',
        mutil: 'MT_ZTW_1_9',
        key: '',
        mainType: 'BTM_ZHENG_TE_WEI',
        subMainType: 'SBTZTW_NUM',
        subTypeName: CMD_3402.emBetSubTypeNames[6],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '8尾',
        mutil: 'MT_ZTW_1_9',
        key: '',
        mainType: 'BTM_ZHENG_TE_WEI',
        subMainType: 'SBTZTW_NUM',
        subTypeName: CMD_3402.emBetSubTypeNames[6],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '9尾',
        mutil: 'MT_ZTW_1_9',
        key: '',
        mainType: 'BTM_ZHENG_TE_WEI',
        subMainType: 'SBTZTW_NUM',
        subTypeName: CMD_3402.emBetSubTypeNames[6],
        cls: styels['t-nomal'],
        topType: 'none',
      },
    ]
  },
  {
    title: '连尾',
    paneKey: '18',
    list: [
      {
        text: '二尾连',
        mutil: 'MT_WSL_ZHONG_2',
        key: '',
        mainType: 'BTM_WEI_SHU_LIAN',
        subMainType: 'SBTWSL_ZHONG_2',
        subTypeName: CMD_3402.emBetSubTypeNames[13],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '三尾连',
        mutil: 'MT_WSL_ZHONG_3',
        key: '',
        mainType: 'BTM_WEI_SHU_LIAN',
        subMainType: 'SBTWSL_ZHONG_3',
        subTypeName: CMD_3402.emBetSubTypeNames[13],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '四尾连',
        mutil: 'MT_WSL_ZHONG_4',
        key: '',
        mainType: 'BTM_WEI_SHU_LIAN',
        subMainType: 'SBTWSL_ZHONG_4',
        subTypeName: CMD_3402.emBetSubTypeNames[13],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '五尾连',
        mutil: 'MT_WSL_ZHONG_5',
        key: '',
        mainType: 'BTM_WEI_SHU_LIAN',
        subMainType: 'SBTWSL_ZHONG_5',
        subTypeName: CMD_3402.emBetSubTypeNames[13],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '二尾连含0',
        mutil: 'MT_WSL_ZHONG_2_0',
        key: '',
        mainType: 'BTM_WEI_SHU_LIAN',
        subMainType: 'SBTWSL_ZHONG_2_0',
        subTypeName: CMD_3402.emBetSubTypeNames[13],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '三尾连含0',
        mutil: 'MT_WSL_ZHONG_3_0',
        key: '',
        mainType: 'BTM_WEI_SHU_LIAN',
        subMainType: 'SBTWSL_ZHONG_3_0',
        subTypeName: CMD_3402.emBetSubTypeNames[13],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '四尾连含0',
        mutil: 'MT_WSL_ZHONG_4_0',
        key: '',
        mainType: 'BTM_WEI_SHU_LIAN',
        subMainType: 'SBTWSL_ZHONG_4_0',
        subTypeName: CMD_3402.emBetSubTypeNames[13],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '五尾连含0',
        mutil: 'MT_WSL_ZHONG_5_0',
        key: '',
        mainType: 'BTM_WEI_SHU_LIAN',
        subMainType: 'SBTWSL_ZHONG_5_0',
        subTypeName: CMD_3402.emBetSubTypeNames[13],
        cls: styels['t-nomal'],
        topType: 'none',
      },
    ]
  },
  {
    title: '连码',
    paneKey: '19',
    list: [
      {
        text: '四全中',
        mutil: 'MT_L_SI_QUAN',
        key: '',
        mainType: 'BTM_LIAN_MA',
        subMainType: 'SBTL_SI_QUAN',
        subTypeName: CMD_3402.emBetSubTypeNames[12],
        cls: styels['t-nomal'],
        topType: 'none',
        child: [
          {
            text: '四全中',
            mutil: 'MT_L_SI_QUAN',
            tMutil: '',
            key: '连码-四全中',
            topType: 'none',
            mainType: 'BTM_LIAN_MA',
            subMainType: 'SBTL_SI_QUAN',
            subTypeName: CMD_3402.emBetSubTypeNames[12],
            cls: styels['t-nomal'],
          },
        ]
      },
      {
        text: '三全中',
        mutil: 'MT_L_SAN_QUAN',
        key: '',
        mainType: 'BTM_LIAN_MA',
        subMainType: 'SBTL_SAN_QUAN',
        subTypeName: CMD_3402.emBetSubTypeNames[12],
        cls: styels['t-nomal'],
        topType: 'none',
        child: [
          {
            text: '三全中',
            mutil: 'MT_L_SAN_QUAN',
            tMutil: '',
            key: '连码-三全中',
            topType: 'none',
            mainType: 'BTM_LIAN_MA',
            subMainType: 'SBTL_SI_QUAN',
            subTypeName: CMD_3402.emBetSubTypeNames[12],
            cls: styels['t-nomal'],
          },
        ]
      },
      {
        text: '三中二',
        mutil: 'MT_L_SAN_ER',
        key: '',
        mainType: 'BTM_LIAN_MA',
        subMainType: 'SBTL_SAN_ER',
        subTypeName: CMD_3402.emBetSubTypeNames[12],
        cls: styels['t-nomal'],
        topType: 'none',
        child: [
          {
            text: '中二',
            mutil: 'MT_L_SAN_ER',
            tMutil: '',
            key: '连码-中二',
            mainType: 'BTM_LIAN_MA',
            subMainType: 'SBTL_SAN_ER',
            subTypeName: CMD_3402.emBetSubTypeNames[12],
            cls: styels['t-nomal'],
          },
          {
            text: '中三',
            mutil: '',
            tMutil: 'MT_L_SAN_ER_SAN',
            key: '连码-中三',
            mainType: 'BTM_LIAN_MA',
            subMainType: 'SBTL_SAN_ER',
            subTypeName: CMD_3402.emBetSubTypeNames[12],
            cls: styels['t-nomal'],
          },
        ]
      },
      {
        text: '二全中',
        mutil: 'MT_L_ER_QUAN',
        key: '',
        mainType: 'BTM_LIAN_MA',
        subMainType: 'SBTL_ER_QUAN',
        subTypeName: CMD_3402.emBetSubTypeNames[12],
        cls: styels['t-nomal'],
        topType: 'none',
        child: [
          {
            text: '二全中',
            mutil: 'MT_L_ER_QUAN',
            tMutil: '',
            key: '连码-二全中',
            mainType: 'BTM_LIAN_MA',
            subMainType: 'SBTL_ER_QUAN',
            subTypeName: CMD_3402.emBetSubTypeNames[12],
            cls: styels['t-nomal'],
          },
        ]
      },
      {
        text: '二中特',
        mutil: 'MT_L_ER_TE',
        key: '',
        mainType: 'BTM_LIAN_MA',
        subMainType: 'SBTL_ER_TE',
        subTypeName: CMD_3402.emBetSubTypeNames[12],
        cls: styels['t-nomal'],
        topType: 'none',
        child: [
          {
            text: '中特',
            mutil: 'MT_L_ER_TE',
            tMutil: '',
            key: '连码-中特',
            mainType: 'BTM_LIAN_MA',
            subMainType: 'SBTL_ER_TE',
            subTypeName: CMD_3402.emBetSubTypeNames[12],
            cls: styels['t-nomal'],
          },
          {
            text: '中二',
            mutil: '',
            tMutil: 'MT_L_ER_TE_ER',
            key: '连码-中二',
            mainType: 'BTM_LIAN_MA',
            subMainType: 'SBTL_ER_TE',
            subTypeName: CMD_3402.emBetSubTypeNames[12],
            cls: styels['t-nomal'],
          },
        ]
      },
      {
        text: '特串',
        mutil: 'MT_L_TE_CHUAN',
        key: '',
        mainType: 'BTM_LIAN_MA',
        subMainType: 'SBTL_TE_CHUAN',
        subTypeName: CMD_3402.emBetSubTypeNames[12],
        cls: styels['t-nomal'],
        topType: 'none',
        child: [
          {
            text: '特串',
            mutil: 'MT_L_TE_CHUAN',
            tMutil: '',
            key: '连码-特串',
            mainType: 'BTM_LIAN_MA',
            subMainType: 'SBTL_TE_CHUAN',
            subTypeName: CMD_3402.emBetSubTypeNames[12],
            cls: styels['t-nomal'],
          },
        ]
      },
    ]
  },
  {
    title: '全不中',
    paneKey: '20',
    list: [
      {
        text: '五不中',
        mutil: 'MT_QBZ_5',
        key: '',
        mainType: 'BTM_QUAN_BU_ZHONG',
        subMainType: 'SBTQBZ_5',
        subTypeName: CMD_3402.emBetSubTypeNames[14],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '六不中',
        mutil: 'MT_QBZ_6',
        key: '',
        mainType: 'BTM_QUAN_BU_ZHONG',
        subMainType: 'SBTQBZ_6',
        subTypeName: CMD_3402.emBetSubTypeNames[14],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '七不中',
        mutil: 'MT_QBZ_7',
        key: '',
        mainType: 'BTM_QUAN_BU_ZHONG',
        subMainType: 'SBTQBZ_7',
        subTypeName: CMD_3402.emBetSubTypeNames[14],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '八不中',
        mutil: 'MT_QBZ_8',
        key: '',
        mainType: 'BTM_QUAN_BU_ZHONG',
        subMainType: 'SBTQBZ_8',
        subTypeName: CMD_3402.emBetSubTypeNames[14],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '九不中',
        mutil: 'MT_QBZ_9',
        key: '',
        mainType: 'BTM_QUAN_BU_ZHONG',
        subMainType: 'SBTQBZ_9',
        subTypeName: CMD_3402.emBetSubTypeNames[14],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '十不中',
        mutil: 'MT_QBZ_10',
        key: '',
        mainType: 'BTM_QUAN_BU_ZHONG',
        subMainType: 'SBTQBZ_10',
        subTypeName: CMD_3402.emBetSubTypeNames[14],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '十一不中',
        mutil: 'MT_QBZ_11',
        key: '',
        mainType: 'BTM_QUAN_BU_ZHONG',
        subMainType: 'SBTQBZ_11',
        subTypeName: CMD_3402.emBetSubTypeNames[14],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '十二不中',
        mutil: 'MT_QBZ_12',
        key: '',
        mainType: 'BTM_QUAN_BU_ZHONG',
        subMainType: 'SBTQBZ_12',
        subTypeName: CMD_3402.emBetSubTypeNames[14],
        cls: styels['t-nomal'],
        topType: 'none',
      },
    ]
  },
  {
    title: '色波',
    paneKey: '21',
    list: [
      {
        text: '红波',
        mutil: 'MT_BO_HONG',
        key: '',
        mainType: 'BTM_SE_BO',
        subMainType: 'SBTB_HONG',
        subTypeName: CMD_3402.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '蓝波',
        mutil: 'MT_BO_LAN',
        key: '',
        mainType: 'BTM_SE_BO',
        subMainType: 'SBTB_LAN',
        subTypeName: CMD_3402.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '绿波',
        mutil: 'MT_BO_LV',
        key: '',
        mainType: 'BTM_SE_BO',
        subMainType: 'SBTB_LV',
        subTypeName: CMD_3402.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '红单',
        mutil: 'MT_BO_HONG_DAN',
        key: '',
        mainType: 'BTM_SE_BO',
        subMainType: 'SBTB_HONG_DAN',
        subTypeName: CMD_3402.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '红双',
        mutil: 'MT_BO_HONG_SHUANG',
        key: '',
        mainType: 'BTM_SE_BO',
        subMainType: 'SBTB_HONG_SHUANG',
        subTypeName: CMD_3402.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '红大',
        mutil: 'MT_BO_HONG_DA',
        key: '',
        mainType: 'BTM_SE_BO',
        subMainType: 'SBTB_HONG_DA',
        subTypeName: CMD_3402.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '红小',
        mutil: 'MT_BO_HONG_XIAO',
        key: '',
        mainType: 'BTM_SE_BO',
        subMainType: 'SBTB_HONG_XIAO',
        subTypeName: CMD_3402.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '蓝单',
        mutil: 'MT_BO_LAN_DAN',
        key: '',
        mainType: 'BTM_SE_BO',
        subMainType: 'SBTB_LAN_DAN',
        subTypeName: CMD_3402.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '蓝双',
        mutil: 'MT_BO_LAN_SHUANG',
        key: '',
        mainType: 'BTM_SE_BO',
        subMainType: 'SBTB_LAN_SHUANG',
        subTypeName: CMD_3402.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '蓝大',
        mutil: 'MT_BO_LAN_DA',
        key: '',
        mainType: 'BTM_SE_BO',
        subMainType: 'SBTB_LAN_DA',
        subTypeName: CMD_3402.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '蓝小',
        mutil: 'MT_BO_LAN_XIAO',
        key: '',
        mainType: 'BTM_SE_BO',
        subMainType: 'SBTB_LAN_XIAO',
        subTypeName: CMD_3402.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '绿单',
        mutil: 'MT_BO_LV_DAN',
        key: '',
        mainType: 'BTM_SE_BO',
        subMainType: 'SBTB_LV_DAN',
        subTypeName: CMD_3402.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '绿双',
        mutil: 'MT_BO_LV_SHUANG',
        key: '',
        mainType: 'BTM_SE_BO',
        subMainType: 'SBTB_LV_SHUANG',
        subTypeName: CMD_3402.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '绿大',
        mutil: 'MT_BO_LV_DA',
        key: '',
        mainType: 'BTM_SE_BO',
        subMainType: 'SBTB_LV_DA',
        subTypeName: CMD_3402.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '绿小',
        mutil: 'MT_BO_LV_XIAO',
        key: '',
        mainType: 'BTM_SE_BO',
        subMainType: 'SBTB_LV_XIAO',
        subTypeName: CMD_3402.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '红大单',
        mutil: 'MT_BO_HONG_DA_DAN',
        key: '',
        mainType: 'BTM_SE_BO',
        subMainType: 'SBTB_HONG_DA_DAN',
        subTypeName: CMD_3402.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '红大双',
        mutil: 'MT_BO_HONG_DA_SHUANG',
        key: '',
        mainType: 'BTM_SE_BO',
        subMainType: 'SBTB_HONG_DA_SHUANG',
        subTypeName: CMD_3402.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '红小单',
        mutil: 'MT_BO_HONG_XIAO_DAN',
        key: '',
        mainType: 'BTM_SE_BO',
        subMainType: 'SBTB_HONG_XIAO_DAN',
        subTypeName: CMD_3402.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '红小双',
        mutil: 'MT_BO_HONG_XIAO_SHUANG',
        key: '',
        mainType: 'BTM_SE_BO',
        subMainType: 'SBTB_HONG_XIAO_SHUANG',
        subTypeName: CMD_3402.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '蓝大单',
        mutil: 'MT_BO_LAN_DA_DAN',
        key: '',
        mainType: 'BTM_SE_BO',
        subMainType: 'SBTB_LAN_DA_DAN',
        subTypeName: CMD_3402.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '蓝大双',
        mutil: 'MT_BO_LAN_DA_SHUANG',
        key: '',
        mainType: 'BTM_SE_BO',
        subMainType: 'SBTB_LAN_DA_SHUANG',
        subTypeName: CMD_3402.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '蓝小单',
        mutil: 'MT_BO_LAN_XIAO_DAN',
        key: '',
        mainType: 'BTM_SE_BO',
        subMainType: 'SBTB_LAN_XIAO_DAN',
        subTypeName: CMD_3402.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '蓝小双',
        mutil: 'MT_BO_LAN_XIAO_SHUANG',
        key: '',
        mainType: 'BTM_SE_BO',
        subMainType: 'SBTB_LAN_XIAO_SHUANG',
        subTypeName: CMD_3402.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '绿大单',
        mutil: 'MT_BO_LV_DA_DAN',
        key: '',
        mainType: 'BTM_SE_BO',
        subMainType: 'SBTB_LV_DA_DAN',
        subTypeName: CMD_3402.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '绿大双',
        mutil: 'MT_BO_LV_DA_SHUANG',
        key: '',
        mainType: 'BTM_SE_BO',
        subMainType: 'SBTB_LV_DA_SHUANG',
        subTypeName: CMD_3402.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '绿小单',
        mutil: 'MT_BO_LV_XIAO_DAN',
        key: '',
        mainType: 'BTM_SE_BO',
        subMainType: 'SBTB_LV_XIAO_DAN',
        subTypeName: CMD_3402.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: '绿小双',
        mutil: 'MT_BO_LV_XIAO_SHUANG',
        key: '',
        mainType: 'BTM_SE_BO',
        subMainType: 'SBTB_LV_XIAO_SHUANG',
        subTypeName: CMD_3402.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
    ]
  }

];


