import { CMD_2903 } from '@/engine/game/pc/2903/CMD_2903';
import styels from '../index.module.scss';
import { curyearsx } from './constCommon';

// 定义49个号码球
const fourtyNineNums = Array.from({ length: 49 }, (_, index) => {
  if (index < 9) {
    return `0${index + 1}`;
  }
  return index + 1;
});

// 特码文字号码
const textCodeS = [
  {
    text: 'DAN',
    subMainType: 'SBTT_DAN',
    mutil: 'MT_TE_DAN',
    mainType: 'BTM_TE',
    cls: styels['t-nomal'],
    subTypeName: CMD_2903.emBetSubTypeNames[0],
    topType: 'none',
  },
  {
    text: 'DA',
    subMainType: 'SBTT_DA',
    mutil: 'MT_TE_DA',
    mainType: 'BTM_TE',
    cls: styels['t-nomal'],
    subTypeName: CMD_2903.emBetSubTypeNames[0],
    topType: 'none',
  },
  {
    text: 'HE_DAN',
    subMainType: 'SBTT_HE_DAN',
    mutil: 'MT_TE_HE_DAN',
    mainType: 'BTM_TE',
    cls: styels['t-nomal'],
    subTypeName: CMD_2903.emBetSubTypeNames[0],
    topType: 'none',
  },
  {
    text: 'HONG',
    subMainType: 'SBTT_HONG',
    mutil: 'MT_TE_HONG',
    mainType: 'BTM_TE',
    cls: styels['t-nomal'],
    subTypeName: CMD_2903.emBetSubTypeNames[0],
    topType: 'none',
  },
  {
    text: 'LV',
    subMainType: 'SBTT_LV',
    mutil: 'MT_TE_LV',
    mainType: 'BTM_TE',
    cls: styels['t-nomal'],
    subTypeName: CMD_2903.emBetSubTypeNames[0],
    topType: 'none',
  },
  {
    text: 'SHUANG',
    subMainType: 'SBTT_SHUANG',
    mutil: 'MT_TE_SHUANG',
    mainType: 'BTM_TE',
    cls: styels['t-nomal'],
    subTypeName: CMD_2903.emBetSubTypeNames[0],
    topType: 'none',
  },
  {
    text: 'XIAO',
    subMainType: 'SBTT_XIAO',
    mutil: 'MT_TE_XIAO',
    mainType: 'BTM_TE',
    cls: styels['t-nomal'],
    subTypeName: CMD_2903.emBetSubTypeNames[0],
    topType: 'none',
  },
  {
    text: 'HE_SHUANG',
    subMainType: 'SBTT_HE_SHUANG',
    mutil: 'MT_TE_HE_SHUANG',
    mainType: 'BTM_TE',
    cls: styels['t-nomal'],
    subTypeName: CMD_2903.emBetSubTypeNames[0],
    topType: 'none',
  },
  {
    text: 'LAN',
    subMainType: 'SBTT_LAN',
    mutil: 'MT_TE_LAN',
    mainType: 'BTM_TE',
    cls: styels['t-nomal'],
    subTypeName: CMD_2903.emBetSubTypeNames[0],
    topType: 'none',
  },
];

// 正码1~6文字号码
const getZNC = ({ mainType }) => [
  {
    text: 'DAN',
    subMainType: 'SBTZN_DAN',
    mutil: 'MT_ZN_DAN',
    mainType,
    cls: styels['t-nomal'],
    subTypeName: CMD_2903.emBetSubTypeNames[1],
    topType: 'none',
  },
  {
    text: 'DA',
    subMainType: 'SBTZN_DA',
    mutil: 'MT_ZN_DA',
    mainType,
    cls: styels['t-nomal'],
    subTypeName: CMD_2903.emBetSubTypeNames[1],
    topType: 'none',
  },
  {
    text: 'HE_DAN',
    subMainType: 'SBTZN_HE_DAN',
    mutil: 'MT_ZN_HE_DAN',
    mainType,
    cls: styels['t-nomal'],
    subTypeName: CMD_2903.emBetSubTypeNames[1],
    topType: 'none',
  },
  {
    text: 'HONG',
    subMainType: 'SBTZN_HONG',
    mutil: 'MT_ZN_HONG',
    mainType,
    cls: styels['t-nomal'],
    subTypeName: CMD_2903.emBetSubTypeNames[1],
    topType: 'none',
  },
  {
    text: 'LV',
    subMainType: 'SBTZN_LV',
    mutil: 'MT_ZN_LV',
    mainType,
    cls: styels['t-nomal'],
    subTypeName: CMD_2903.emBetSubTypeNames[1],
    topType: 'none',
  },
  {
    text: 'SHUANG',
    subMainType: 'SBTZN_SHUANG',
    mutil: 'MT_ZN_SHUANG',
    mainType,
    cls: styels['t-nomal'],
    subTypeName: CMD_2903.emBetSubTypeNames[1],
    topType: 'none',
  },
  {
    text: 'XIAO',
    subMainType: 'SBTZN_XIAO',
    mutil: 'MT_ZN_XIAO',
    mainType,
    cls: styels['t-nomal'],
    subTypeName: CMD_2903.emBetSubTypeNames[1],
    topType: 'none',
  },
  {
    text: 'HE_SHUANG',
    subMainType: 'SBTZN_HE_SHUANG',
    mutil: 'MT_ZN_HE_SHUANG',
    mainType,
    cls: styels['t-nomal'],
    subTypeName: CMD_2903.emBetSubTypeNames[1],
    topType: 'none',
  },
  {
    text: 'LAN',
    subMainType: 'SBTZN_LAN',
    mutil: 'MT_ZN_LAN',
    mainType,
    cls: styels['t-nomal'],
    subTypeName: CMD_2903.emBetSubTypeNames[1],
    topType: 'none',
  },
];

// 生肖
const shengxiao = {
  shu: [4, 16, 28, 40],
  niu: [3, 15, 27, 39],
  hu: [2, 14, 26, 38],
  tu: [1, 13, 25, 37, 49],
  long: [12, 24, 36, 48],
  she: [11, 23, 35, 47],
  ma: [10, 22, 34, 46],
  yang: [9, 21, 33, 45],
  hou: [8, 20, 32, 44],
  ji: [7, 19, 31, 43],
  gou: [6, 18, 30, 42],
  zhu: [5, 17, 29, 41],
};

// 尾数map
const wsCodeMap = {
  one: [1, 11, 21, 31, 41],
  tu: [2, 12, 22, 32, 42],
  three: [3, 13, 23, 33, 43],
  four: [4, 14, 24, 34, 44],
  five: [5, 15, 25, 35, 45],
  six: [6, 16, 26, 36, 46],
  serven: [7, 17, 27, 37, 47],
  eight: [8, 18, 28, 38, 48],
  nine: [9, 19, 29, 39, 49],
  zero: [10, 20, 30, 40],
};

//半波
const redSingle = [1, 7, 13, 19, 23, 29, 35, 45];
const redDouble = [2, 8, 12, 18, 24, 30, 34, 40, 46];
const redBig = [29, 30, 34, 35, 40, 45, 46];
const redSmall = [1, 2, 7, 8, 12, 13, 18, 19, 23, 24];
const blueSingle = [3, 9, 15, 25, 31, 37, 41, 47];
const blueDouble = [4, 10, 14, 20, 26, 36, 42, 48];
const blueBig = [25, 26, 31, 36, 37, 41, 42, 47, 48];
const blueSmall = [3, 4, 9, 10, 14, 15, 20];
const greenSingle = [5, 11, 17, 21, 27, 33, 39, 43, 49];
const greenDouble = [6, 16, 22, 28, 32, 38, 44];
const greenBig = [27, 28, 32, 33, 38, 39, 43, 44, 49];
const greenSmall = [5, 6, 11, 16, 17, 21, 22];

// 半波
export const banBo = [
  redSingle,
  redDouble,
  redBig,
  redSmall,
  blueSingle,
  blueDouble,
  blueBig,
  blueSmall,
  greenSingle,
  greenDouble,
  greenBig,
  greenSmall,
];

// 1-49 号码配置
const getNumlist = (
  { mutil, mainType, subMainType, subTypeName },
  len?: number
) => {
  const numList = [];
  (len ? fourtyNineNums.slice(0, len) : fourtyNineNums).forEach((item, i) => {
    numList.push({
      text: `${item}`,
      mutil: typeof mutil === 'function' ? mutil(i) : mutil,
      key: '',
      mainType,
      subMainType,
      subTypeName,
      cls: styels['t-nomal'],
    });
  });
  return numList;
};

// 2903 content 按钮快 ：展示常量
export const tabListFirst = [
  {
    title: 'TE',
    key: '0',
    listKey: 'tmArr',
  },
  {
    title: 'ZM_1',
    key: '1',
    listKey: 'zmOneArr',
  },
  {
    title: 'ZM_2',
    key: '2',
    listKey: 'zmTwoArr',
  },
  {
    title: 'ZM_3',
    key: '4',
    listKey: 'zmThreeArr',
  },
  {
    title: 'ZM_4',
    key: '5',
    listKey: 'zmFourArr',
  },
  {
    title: 'ZM_5',
    key: '6',
    listKey: 'zmFiveArr',
  },
  {
    title: 'ZM_6',
    key: '7',
    listKey: 'zmSixArr',
  },
  {
    title: 'ZM',
    key: '8',
    listKey: 'zmArr',
  },
  {
    title: 'BB',
    key: '9',
    listKey: 'bbArr',
  },
  {
    title: 'TX',
    key: '10',
    listKey: 'txArr',
  },
  {
    title: 'YX',
    key: '11',
    listKey: 'yxArr',
  },
  {
    title: 'ZTW',
    key: '12',
    listKey: 'ztwArr',
    ballType: 'none',
  },
  {
    title: 'LM',
    key: '13',
    listKey: 'lmaArr',
  },
  {
    title: 'HX',
    key: '14',
    listKey: 'hxArr',
  },
  {
    title: 'SXL',
    key: '15',
    listKey: 'sxlArr',
  },
  {
    title: 'WSL',
    key: '16',
    listKey: 'wslArr',
  },
  {
    title: 'QBZ',
    key: '17',
    listKey: 'qbzArr',
  },
];

interface ListProps {
  text: string;
  mutil: string;
  key?: string;
  mainType: string;
  subMainType: string;
  subTypeName: string;
  cls?: any;
  topType?: string;
  child?: any[];
}
interface BetNumberListProps {
  title: string;
  paneKey: string;
  list: ListProps[];
}

// 3402 content 按钮快 ：展示常量
export const betNumberList: BetNumberListProps[] = [
  {
    title: 'TE',
    paneKey: '1',
    list: [
      ...getNumlist({
        mutil: 'MT_TE_NUM',
        mainType: 'BTM_TE',
        subMainType: 'SBTT_NUM',
        subTypeName: CMD_2903.emBetSubTypeNames[0],
      }),
      ...textCodeS.map((it) => ({ ...it })),
    ],
  },
  {
    title: 'ZM_1',
    paneKey: '2',
    list: [
      ...getNumlist({
        mutil: 'MT_ZN_NUM',
        mainType: 'BTM_ZHENG_1',
        subMainType: 'SBTZN_NUM',
        subTypeName: CMD_2903.emBetSubTypeNames[1],
      }),
      ...getZNC({ mainType: 'BTM_ZHENG_1' }).map((it) => ({ ...it })),
    ],
  },

  {
    title: 'ZM_2',
    paneKey: '3',
    list: [
      ...getNumlist({
        mutil: 'MT_ZN_NUM',
        mainType: 'BTM_ZHENG_2',
        subMainType: 'SBTZN_NUM',
        subTypeName: CMD_2903.emBetSubTypeNames[1],
      }),
      ...getZNC({ mainType: 'BTM_ZHENG_2' }).map((it) => ({ ...it })),
    ],
  },
  {
    title: 'ZM_3',
    paneKey: '4',
    list: [
      ...getNumlist({
        mutil: 'MT_ZN_NUM',
        mainType: 'BTM_ZHENG_3',
        subMainType: 'SBTZN_NUM',
        subTypeName: CMD_2903.emBetSubTypeNames[1],
      }),
      ...getZNC({ mainType: 'BTM_ZHENG_3' }).map((it) => ({ ...it })),
    ],
  },
  {
    title: 'ZM_4',
    paneKey: '5',
    list: [
      ...getNumlist({
        mutil: 'MT_ZN_NUM',
        mainType: 'BTM_ZHENG_4',
        subMainType: 'SBTZN_NUM',
        subTypeName: CMD_2903.emBetSubTypeNames[1],
      }),
      ...getZNC({ mainType: 'BTM_ZHENG_4' }).map((it) => ({ ...it })),
    ],
  },
  {
    title: 'ZM_5',
    paneKey: '6',
    list: [
      ...getNumlist({
        mutil: 'MT_ZN_NUM',
        mainType: 'BTM_ZHENG_5',
        subMainType: 'SBTZN_NUM',
        subTypeName: CMD_2903.emBetSubTypeNames[1],
      }),
      ...getZNC({ mainType: 'BTM_ZHENG_5' }).map((it) => ({ ...it })),
    ],
  },
  {
    title: 'ZM_6',
    paneKey: '7',
    list: [
      ...getNumlist({
        mutil: 'MT_ZN_NUM',
        mainType: 'BTM_ZHENG_6',
        subMainType: 'SBTZN_NUM',
        subTypeName: CMD_2903.emBetSubTypeNames[1],
      }),
      ...getZNC({ mainType: 'BTM_ZHENG_6' }).map((it) => ({ ...it })),
    ],
  },

  {
    title: 'ZM',
    paneKey: '8',
    list: [
      ...getNumlist({
        mutil: 'MT_ZHENG_NUM',
        mainType: 'BTM_ZHENG',
        subMainType: 'SBTZ_NUM',
        subTypeName: CMD_2903.emBetSubTypeNames[2],
      }),
      {
        text: 'ZONG_DAN',
        mutil: 'MT_HE_DAN',
        key: '',
        mainType: 'BTM_HE',
        subMainType: 'SBTH_DAN',
        subTypeName: CMD_2903.emBetSubTypeNames[3],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'ZONG_SHUANG',
        mutil: 'MT_HE_SHUANG',
        key: '',
        mainType: 'BTM_HE',
        subMainType: 'SBTH_SHUANG',
        subTypeName: CMD_2903.emBetSubTypeNames[3],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'ZONG_DA',
        mutil: 'MT_HE_DA',
        key: '',
        mainType: 'BTM_HE',
        subMainType: 'SBTH_DA',
        subTypeName: CMD_2903.emBetSubTypeNames[3],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'ZONG_XIAO',
        mutil: 'MT_HE_XIAO',
        key: '',
        mainType: 'BTM_HE',
        subMainType: 'SBTH_XIAO',
        subTypeName: CMD_2903.emBetSubTypeNames[3],
        cls: styels['t-nomal'],
        topType: 'none',
      },
    ],
  },
  {
    title: 'BB',
    paneKey: '9',
    list: [
      {
        text: 'HONG_DAN',
        numList: redSingle,
        mutil: 'MT_B_HONG_DAN',
        key: '',
        mainType: 'BTM_BAN_BO',
        subMainType: 'SBTB_HONG_DAN',
        subTypeName: CMD_2903.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'HONG_SHUANG',
        numList: redDouble,
        mutil: 'MT_B_HONG_SHUANG',
        key: '',
        mainType: 'BTM_BAN_BO',
        subMainType: 'SBTB_HONG_SHUANG',
        subTypeName: CMD_2903.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'HONG_DA',
        numList: redBig,
        mutil: 'MT_B_HONG_DA',
        key: '',
        mainType: 'BTM_BAN_BO',
        subMainType: 'SBTB_HONG_DA',
        subTypeName: CMD_2903.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'HONG_XIAO',
        numList: redSmall,
        mutil: 'MT_B_HONG_XIAO',
        key: '',
        mainType: 'BTM_BAN_BO',
        subMainType: 'SBTB_HONG_XIAO',
        subTypeName: CMD_2903.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'LAN_DAN',
        numList: blueSingle,
        mutil: 'MT_B_LAN_DAN',
        key: '',
        mainType: 'BTM_BAN_BO',
        subMainType: 'SBTB_LAN_DAN',
        subTypeName: CMD_2903.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'LAN_SHUANG',
        numList: blueDouble,
        mutil: 'MT_B_LAN_SHUANG',
        key: '',
        mainType: 'BTM_BAN_BO',
        subMainType: 'SBTB_LAN_SHUANG',
        subTypeName: CMD_2903.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'LAN_DA',
        numList: blueBig,
        mutil: 'MT_B_LAN_DA',
        key: '',
        mainType: 'BTM_BAN_BO',
        subMainType: 'SBTB_LAN_DA',
        subTypeName: CMD_2903.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'LAN_XIAO',
        numList: blueSmall,
        mutil: 'MT_B_LAN_XIAO',
        key: '',
        mainType: 'BTM_BAN_BO',
        subMainType: 'SBTB_LAN_XIAO',
        subTypeName: CMD_2903.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'LV_DAN',
        numList: greenSingle,
        mutil: 'MT_B_LV_DAN',
        key: '',
        mainType: 'BTM_BAN_BO',
        subMainType: 'SBTB_LV_DAN',
        subTypeName: CMD_2903.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'LV_SHUANG',
        numList: greenDouble,
        mutil: 'MT_B_LV_SHUANG',
        key: '',
        mainType: 'BTM_BAN_BO',
        subMainType: 'SBTB_LV_SHUANG',
        subTypeName: CMD_2903.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'LV_DA',
        numList: greenBig,
        mutil: 'MT_B_LV_DA',
        key: '',
        mainType: 'BTM_BAN_BO',
        subMainType: 'SBTB_LV_DA',
        subTypeName: CMD_2903.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'LV_XIAO',
        numList: greenSmall,
        mutil: 'MT_B_LV_XIAO',
        key: '',
        mainType: 'BTM_BAN_BO',
        subMainType: 'SBTB_LV_XIAO',
        subTypeName: CMD_2903.emBetSubTypeNames[4],
        cls: styels['t-nomal'],
        topType: 'none',
      },
    ],
  },
  {
    title: 'TX',
    paneKey: '10',
    list: [
      {
        text: 'SHU',
        numList: shengxiao.shu,
        mutil: 'MT_TX_SHU',
        key: '',
        mainType: 'BTM_TE_XIAO',
        subMainType: 'XT_SHU',
        subTypeName: CMD_2903.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'NIU',
        numList: shengxiao.niu,
        mutil: 'MT_TX_NIU',
        key: '',
        mainType: 'BTM_TE_XIAO',
        subMainType: 'XT_NIU',
        subTypeName: CMD_2903.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'HU',
        numList: shengxiao.hu,
        mutil: 'MT_TX_HU',
        key: '',
        mainType: 'BTM_TE_XIAO',
        subMainType: 'XT_HU',
        subTypeName: CMD_2903.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'TU',
        numList: shengxiao.tu,
        mutil: 'MT_TX_TU',
        key: '',
        mainType: 'BTM_TE_XIAO',
        subMainType: 'XT_TU',
        subTypeName: CMD_2903.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'LONG',
        numList: shengxiao.long,
        mutil: 'MT_TX_LONG',
        key: '',
        mainType: 'BTM_TE_XIAO',
        subMainType: 'XT_LONG',
        subTypeName: CMD_2903.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'SHE',
        numList: shengxiao.she,
        mutil: 'MT_TX_SHE',
        key: '',
        mainType: 'BTM_TE_XIAO',
        subMainType: 'XT_SHE',
        subTypeName: CMD_2903.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'MA',
        numList: shengxiao.ma,
        mutil: 'MT_TX_MA',
        key: '',
        mainType: 'BTM_TE_XIAO',
        subMainType: 'XT_MA',
        subTypeName: CMD_2903.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'YANG',
        numList: shengxiao.yang,
        mutil: 'MT_TX_YANG',
        key: '',
        mainType: 'BTM_TE_XIAO',
        subMainType: 'XT_YANG',
        subTypeName: CMD_2903.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'HOU',
        numList: shengxiao.hou,
        mutil: 'MT_TX_HOU',
        key: '',
        mainType: 'BTM_TE_XIAO',
        subMainType: 'XT_HOU',
        subTypeName: CMD_2903.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'JI',
        numList: shengxiao.ji,
        mutil: 'MT_TX_ZI',
        key: '',
        mainType: 'BTM_TE_XIAO',
        subMainType: 'XT_JI',
        subTypeName: CMD_2903.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'GOU',
        numList: shengxiao.gou,
        mutil: 'MT_TX_GOU',
        key: '',
        mainType: 'BTM_TE_XIAO',
        subMainType: 'XT_GOU',
        subTypeName: CMD_2903.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'ZHU',
        numList: shengxiao.zhu,
        mutil: 'MT_TX_ZHU',
        key: '',
        mainType: 'BTM_TE_XIAO',
        subMainType: 'XT_ZHU',
        subTypeName: CMD_2903.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
    ],
  },
  {
    title: 'YX',
    paneKey: '11',
    list: [
      {
        text: 'SHU',
        numList: shengxiao.shu,
        mutil: 'MT_YX_SHU',
        key: '',
        mainType: 'BTM_YI_XIAO',
        subMainType: 'XT_SHU',
        subTypeName: CMD_2903.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'NIU',
        numList: shengxiao.niu,
        mutil: 'MT_YX_NIU',
        key: '',
        mainType: 'BTM_YI_XIAO',
        subMainType: 'XT_NIU',
        subTypeName: CMD_2903.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'HU',
        numList: shengxiao.hu,
        mutil: 'MT_YX_HU',
        key: '',
        mainType: 'BTM_YI_XIAO',
        subMainType: 'XT_HU',
        subTypeName: CMD_2903.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'TU',
        numList: shengxiao.tu,
        mutil: 'MT_YX_TU',
        key: '',
        mainType: 'BTM_YI_XIAO',
        subMainType: 'XT_TU',
        subTypeName: CMD_2903.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'LONG',
        numList: shengxiao.long,
        mutil: 'MT_YX_LONG',
        key: '',
        mainType: 'BTM_YI_XIAO',
        subMainType: 'XT_LONG',
        subTypeName: CMD_2903.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'SHE',
        numList: shengxiao.she,
        mutil: 'MT_YX_SHE',
        key: '',
        mainType: 'BTM_YI_XIAO',
        subMainType: 'XT_SHE',
        subTypeName: CMD_2903.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'MA',
        numList: shengxiao.ma,
        mutil: 'MT_YX_MA',
        key: '',
        mainType: 'BTM_YI_XIAO',
        subMainType: 'XT_MA',
        subTypeName: CMD_2903.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'YANG',
        numList: shengxiao.yang,
        mutil: 'MT_YX_YANG',
        key: '',
        mainType: 'BTM_YI_XIAO',
        subMainType: 'XT_YANG',
        subTypeName: CMD_2903.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'HOU',
        numList: shengxiao.hou,
        mutil: 'MT_YX_HOU',
        key: '',
        mainType: 'BTM_YI_XIAO',
        subMainType: 'XT_HOU',
        subTypeName: CMD_2903.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'JI',
        numList: shengxiao.ji,
        mutil: 'MT_YX_ZI',
        key: '',
        mainType: 'BTM_YI_XIAO',
        subMainType: 'XT_JI',
        subTypeName: CMD_2903.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'GOU',
        numList: shengxiao.gou,
        mutil: 'MT_YX_GOU',
        key: '',
        mainType: 'BTM_YI_XIAO',
        subMainType: 'XT_GOU',
        subTypeName: CMD_2903.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'ZHU',
        numList: shengxiao.zhu,
        mutil: 'MT_YX_ZHU',
        key: '',
        mainType: 'BTM_YI_XIAO',
        subMainType: 'XT_ZHU',
        subTypeName: CMD_2903.emBetSubTypeNames[5],
        cls: styels['t-nomal'],
        topType: 'none',
      },
    ],
  },
  {
    title: 'ZTW',
    paneKey: '12',
    list: [
      {
        text: '0',
        mutil: 'MT_ZTW_0',
        key: '',
        mainType: 'BTM_ZHENG_TE_WEI',
        subMainType: 'SBTZTW_NUM',
        subTypeName: CMD_2903.emBetSubTypeNames[6],
      },
      ...getNumlist(
        {
          mutil: (i) => `MT_ZTW_${i + 1}`,
          mainType: 'BTM_ZHENG_TE_WEI',
          subMainType: 'SBTZTW_NUM',
          subTypeName: CMD_2903.emBetSubTypeNames[6],
        },
        9
      ),
    ],
  },
  {
    title: 'LM',
    paneKey: '13',
    list: [
      {
        text: 'SI_QUAN_ZHOGN',
        mutil: 'MT_L_SI_QUAN',
        key: '',
        mainType: 'BTM_LIAN_MA',
        subMainType: 'SBTL_SI_QUAN',
        subTypeName: CMD_2903.emBetSubTypeNames[7],
        cls: styels['t-nomal'],
        topType: 'none',
        child: [
          {
            text: 'SI_QUAN_ZHOGN',
            mutil: 'MT_L_SI_QUAN',
            tMutil: '',
            key: 'LM_SI_QUAN_ZHOGN',
            topType: 'none',
            mainType: 'BTM_LIAN_MA',
            subMainType: 'SBTL_SI_QUAN',
            subTypeName: CMD_2903.emBetSubTypeNames[7],
            cls: styels['t-nomal'],
          },
        ],
      },
      {
        text: 'SAN_QUAN_ZHOGN',
        mutil: 'MT_L_SAN_QUAN',
        key: '',
        mainType: 'BTM_LIAN_MA',
        subMainType: 'SBTL_SAN_QUAN',
        subTypeName: CMD_2903.emBetSubTypeNames[7],
        cls: styels['t-nomal'],
        topType: 'none',
        child: [
          {
            text: 'SAN_QUAN_ZHOGN',
            mutil: 'MT_L_SAN_QUAN',
            tMutil: '',
            key: 'LM_SAN_QUAN_ZHOGN',
            topType: 'none',
            mainType: 'BTM_LIAN_MA',
            subMainType: 'SBTL_SAN_QUAN',
            subTypeName: CMD_2903.emBetSubTypeNames[7],
            cls: styels['t-nomal'],
          },
        ],
      },
      {
        text: 'SAN_ZHOGN_ER',
        mutil: 'MT_L_SAN_ER',
        key: '',
        mainType: 'BTM_LIAN_MA',
        subMainType: 'SBTL_SAN_ER',
        subTypeName: CMD_2903.emBetSubTypeNames[7],
        topType: 'none',
        child: [
          {
            text: 'ZHOGN_ER',
            mutil: 'MT_L_SAN_ER',
            tMutil: '',
            key: 'LM_ZHOGN_ER',
            mainType: 'BTM_LIAN_MA',
            subMainType: 'SBTL_SAN_ER',
            subTypeName: CMD_2903.emBetSubTypeNames[7],
          },
          {
            text: 'ZHOGN_SAN',
            mutil: 'MT_L_SAN_ER_SAN',
            tMutil: 'MT_L_SAN_ER_SAN',
            key: 'LM_ZHOGN_SAN',
            mainType: 'BTM_LIAN_MA',
            subMainType: 'SBTL_SAN_ER',
            subTypeName: CMD_2903.emBetSubTypeNames[7],
          },
        ],
      },
      {
        text: 'ER_QUAN_ZHOGN',
        mutil: 'MT_L_ER_QUAN',
        key: '',
        mainType: 'BTM_LIAN_MA',
        subMainType: 'SBTL_ER_QUAN',
        subTypeName: CMD_2903.emBetSubTypeNames[7],
        cls: styels['t-nomal'],
        topType: 'none',
        child: [
          {
            text: 'ER_QUAN_ZHOGN',
            mutil: 'MT_L_ER_QUAN',
            tMutil: '',
            key: 'LM_ER_QUAN_ZHOGN',
            mainType: 'BTM_LIAN_MA',
            subMainType: 'SBTL_ER_QUAN',
            subTypeName: CMD_2903.emBetSubTypeNames[7],
            cls: styels['t-nomal'],
          },
        ],
      },
      {
        text: 'ER_ZHONG_TE',
        mutil: 'MT_L_ER_TE',
        key: '',
        mainType: 'BTM_LIAN_MA',
        subMainType: 'SBTL_ER_TE',
        subTypeName: CMD_2903.emBetSubTypeNames[7],
        cls: styels['t-nomal'],
        topType: 'none',
        child: [
          {
            text: 'ZHONG_TE',
            mutil: 'MT_L_ER_TE',
            tMutil: '',
            key: 'LM_ZHONG_TE',
            mainType: 'BTM_LIAN_MA',
            subMainType: 'SBTL_ER_TE',
            subTypeName: CMD_2903.emBetSubTypeNames[7],
            cls: styels['t-nomal'],
          },
          {
            text: 'ZHOGN_ER',
            mutil: 'MT_L_ER_TE_ER',
            tMutil: 'MT_L_ER_TE_ER',
            key: 'LM_ZHOGN_ER',
            mainType: 'BTM_LIAN_MA',
            subMainType: 'SBTL_ER_TE',
            subTypeName: CMD_2903.emBetSubTypeNames[7],
            cls: styels['t-nomal'],
          },
        ],
      },
      {
        text: 'TE_CHUAN',
        mutil: 'MT_L_TE_CHUAN',
        key: '',
        mainType: 'BTM_LIAN_MA',
        subMainType: 'SBTL_TE_CHUAN',
        subTypeName: CMD_2903.emBetSubTypeNames[7],
        cls: styels['t-nomal'],
        topType: 'none',
        child: [
          {
            text: 'TE_CHUAN',
            mutil: 'MT_L_TE_CHUAN',
            tMutil: '',
            key: 'LM_TE_CHUAN',
            mainType: 'BTM_LIAN_MA',
            subMainType: 'SBTL_TE_CHUAN',
            subTypeName: CMD_2903.emBetSubTypeNames[7],
            cls: styels['t-nomal'],
          },
        ],
      },
    ],
  },
  {
    title: 'HX',
    paneKey: '14',
    list: [
      {
        text: 'SHU',
        numList: shengxiao.shu,
        mutil: '',
        key: '',
        mainType: 'BTM_HE_XIAO',
        subMainType: '',
        subTypeName: CMD_2903.emBetSubTypeNames[8],
      },
      {
        text: 'NIU',
        numList: shengxiao.niu,
        mutil: '',
        key: '',
        mainType: 'BTM_HE_XIAO',
        subMainType: '',
        subTypeName: CMD_2903.emBetSubTypeNames[8],
      },
      {
        text: 'HU',
        numList: shengxiao.hu,
        mutil: 'MT_YX_HU',
        key: '',
        mainType: 'BTM_HE_XIAO',
        subMainType: '',
        subTypeName: CMD_2903.emBetSubTypeNames[8],
      },
      {
        text: 'TU',
        numList: shengxiao.tu,
        mutil: 'MT_YX_TU',
        key: '',
        mainType: 'BTM_HE_XIAO',
        subMainType: '',
        subTypeName: CMD_2903.emBetSubTypeNames[8],
      },
      {
        text: 'LONG',
        numList: shengxiao.long,
        mutil: 'MT_YX_LONG',
        key: '',
        mainType: 'BTM_HE_XIAO',
        subMainType: '',
        subTypeName: CMD_2903.emBetSubTypeNames[8],
      },
      {
        text: 'SHE',
        numList: shengxiao.she,
        mutil: 'MT_YX_SHE',
        key: '',
        mainType: 'BTM_HE_XIAO',
        subMainType: '',
        subTypeName: CMD_2903.emBetSubTypeNames[8],
      },
      {
        text: 'MA',
        numList: shengxiao.ma,
        mutil: 'MT_YX_MA',
        key: '',
        mainType: 'BTM_HE_XIAO',
        subMainType: '',
        subTypeName: CMD_2903.emBetSubTypeNames[8],
      },
      {
        text: 'YANG',
        numList: shengxiao.yang,
        mutil: 'MT_YX_YANG',
        key: '',
        mainType: 'BTM_HE_XIAO',
        subMainType: '',
        subTypeName: CMD_2903.emBetSubTypeNames[8],
      },
      {
        text: 'HOU',
        numList: shengxiao.hou,
        mutil: 'MT_YX_HOU',
        key: '',
        mainType: 'BTM_HE_XIAO',
        subMainType: '',
        subTypeName: CMD_2903.emBetSubTypeNames[8],
      },
      {
        text: 'JI',
        numList: shengxiao.ji,
        mutil: 'MT_YX_ZI',
        key: '',
        mainType: 'BTM_HE_XIAO',
        subMainType: '',
        subTypeName: CMD_2903.emBetSubTypeNames[8],
      },
      {
        text: 'GOU',
        numList: shengxiao.gou,
        mutil: 'MT_YX_GOU',
        key: '',
        mainType: 'BTM_HE_XIAO',
        subMainType: '',
        subTypeName: CMD_2903.emBetSubTypeNames[8],
      },
      {
        text: 'ZHU',
        numList: shengxiao.zhu,
        mutil: 'MT_YX_ZHU',
        key: '',
        mainType: 'BTM_HE_XIAO',
        subMainType: '',
        subTypeName: CMD_2903.emBetSubTypeNames[8],
      },
    ],
  },
  {
    title: 'SXL',
    paneKey: '15',
    list: [
      {
        text: 'SHU',
        idx: 0,
        numList: shengxiao.shu,
        mainType: 'BTM_SHENG_XIAO_LIAN',
        subTypeName: CMD_2903.emBetSubTypeNames[9],
      },
      {
        text: 'NIU',
        idx: 1,
        numList: shengxiao.niu,
        mainType: 'BTM_SHENG_XIAO_LIAN',
        subTypeName: CMD_2903.emBetSubTypeNames[9],
      },
      {
        text: 'HU',
        idx: 2,
        numList: shengxiao.hu,
        mainType: 'BTM_SHENG_XIAO_LIAN',
        subTypeName: CMD_2903.emBetSubTypeNames[9],
      },
      {
        text: 'TU',
        idx: 3,
        numList: shengxiao.tu,
        mainType: 'BTM_SHENG_XIAO_LIAN',
        subTypeName: CMD_2903.emBetSubTypeNames[9],
      },
      {
        text: 'LONG',
        idx: 4,
        numList: shengxiao.long,
        mainType: 'BTM_SHENG_XIAO_LIAN',
        subTypeName: CMD_2903.emBetSubTypeNames[9],
      },
      {
        text: 'SHE',
        idx: 5,
        numList: shengxiao.she,
        mainType: 'BTM_SHENG_XIAO_LIAN',
        subTypeName: CMD_2903.emBetSubTypeNames[9],
      },
      {
        text: 'MA',
        idx: 6,
        numList: shengxiao.ma,
        mainType: 'BTM_SHENG_XIAO_LIAN',
        subTypeName: CMD_2903.emBetSubTypeNames[9],
      },
      {
        text: 'YANG',
        idx: 7,
        numList: shengxiao.yang,
        mainType: 'BTM_SHENG_XIAO_LIAN',
        subTypeName: CMD_2903.emBetSubTypeNames[9],
      },
      {
        text: 'HOU',
        idx: 8,
        numList: shengxiao.hou,
        mainType: 'BTM_SHENG_XIAO_LIAN',
        subTypeName: CMD_2903.emBetSubTypeNames[9],
      },
      {
        text: 'JI',
        idx: 9,
        numList: shengxiao.ji,
        mainType: 'BTM_SHENG_XIAO_LIAN',
        subTypeName: CMD_2903.emBetSubTypeNames[9],
      },
      {
        text: 'GOU',
        idx: 10,
        numList: shengxiao.gou,
        mainType: 'BTM_SHENG_XIAO_LIAN',
        subTypeName: CMD_2903.emBetSubTypeNames[9],
      },
      {
        text: 'ZHU',
        idx: 11,
        numList: shengxiao.zhu,
        mainType: 'BTM_SHENG_XIAO_LIAN',
        subTypeName: CMD_2903.emBetSubTypeNames[9],
      },
    ],
  },

  {
    title: 'WSL',
    paneKey: '16',
    list: [
      {
        text: 1,
        idx: 1,
        numList: wsCodeMap.one,
        mainType: 'BTM_WEI_SHU_LIAN',
        subTypeName: CMD_2903.emBetSubTypeNames[10],
      },
      {
        text: 6,
        idx: 6,
        numList: wsCodeMap.six,
        mainType: 'BTM_WEI_SHU_LIAN',
        subTypeName: CMD_2903.emBetSubTypeNames[10],
      },
      {
        text: 2,
        idx: 2,
        numList: wsCodeMap.tu,
        mainType: 'BTM_WEI_SHU_LIAN',
        subTypeName: CMD_2903.emBetSubTypeNames[10],
      },
      {
        text: 7,
        idx: 7,
        numList: wsCodeMap.serven,
        mainType: 'BTM_WEI_SHU_LIAN',
        subTypeName: CMD_2903.emBetSubTypeNames[10],
      },
      {
        text: 3,
        idx: 3,
        numList: wsCodeMap.three,
        mainType: 'BTM_WEI_SHU_LIAN',
        subTypeName: CMD_2903.emBetSubTypeNames[10],
      },
      {
        text: 8,
        idx: 8,
        numList: wsCodeMap.eight,
        mainType: 'BTM_WEI_SHU_LIAN',
        subTypeName: CMD_2903.emBetSubTypeNames[10],
      },
      {
        text: 4,
        idx: 4,
        numList: wsCodeMap.four,
        mainType: 'BTM_WEI_SHU_LIAN',
        subTypeName: CMD_2903.emBetSubTypeNames[10],
      },
      {
        text: 9,
        idx: 9,
        numList: wsCodeMap.nine,
        mainType: 'BTM_WEI_SHU_LIAN',
        subTypeName: CMD_2903.emBetSubTypeNames[10],
      },
      {
        text: 5,
        idx: 5,
        numList: wsCodeMap.five,
        mainType: 'BTM_WEI_SHU_LIAN',
        subTypeName: CMD_2903.emBetSubTypeNames[10],
      },
      {
        text: 0,
        idx: 0,
        numList: wsCodeMap.zero,
        mainType: 'BTM_WEI_SHU_LIAN',
        subTypeName: CMD_2903.emBetSubTypeNames[10],
      },
    ],
  },
  {
    title: 'QBZ',
    paneKey: '17',
    list: [
      {
        text: 'BU_ZHONG_5',
        mutil: 'MT_QBZ_5',
        key: '',
        mainType: 'BTM_QUAN_BU_ZHONG',
        subMainType: 'SBTQBZ_5',
        subTypeName: CMD_2903.emBetSubTypeNames[11],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'BU_ZHONG_6',
        mutil: 'MT_QBZ_6',
        key: '',
        mainType: 'BTM_QUAN_BU_ZHONG',
        subMainType: 'SBTQBZ_6',
        subTypeName: CMD_2903.emBetSubTypeNames[11],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'BU_ZHONG_7',
        mutil: 'MT_QBZ_7',
        key: '',
        mainType: 'BTM_QUAN_BU_ZHONG',
        subMainType: 'SBTQBZ_7',
        subTypeName: CMD_2903.emBetSubTypeNames[11],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'BU_ZHONG_8',
        mutil: 'MT_QBZ_8',
        key: '',
        mainType: 'BTM_QUAN_BU_ZHONG',
        subMainType: 'SBTQBZ_8',
        subTypeName: CMD_2903.emBetSubTypeNames[11],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'BU_ZHONG_9',
        mutil: 'MT_QBZ_9',
        key: '',
        mainType: 'BTM_QUAN_BU_ZHONG',
        subMainType: 'SBTQBZ_9',
        subTypeName: CMD_2903.emBetSubTypeNames[11],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'BU_ZHONG_10',
        mutil: 'MT_QBZ_10',
        key: '',
        mainType: 'BTM_QUAN_BU_ZHONG',
        subMainType: 'SBTQBZ_10',
        subTypeName: CMD_2903.emBetSubTypeNames[11],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'BU_ZHONG_11',
        mutil: 'MT_QBZ_11',
        key: '',
        mainType: 'BTM_QUAN_BU_ZHONG',
        subMainType: 'SBTQBZ_11',
        subTypeName: CMD_2903.emBetSubTypeNames[11],
        cls: styels['t-nomal'],
        topType: 'none',
      },
      {
        text: 'BU_ZHONG_12',
        mutil: 'MT_QBZ_12',
        key: '',
        mainType: 'BTM_QUAN_BU_ZHONG',
        subMainType: 'SBTQBZ_12',
        subTypeName: CMD_2903.emBetSubTypeNames[11],
        cls: styels['t-nomal'],
        topType: 'none',
      },
    ],
  },
];

// 合肖 子码对应关系 key: 中、不中首字母 + 选项条数
export const subBetTypeMap = {
  z1: { sub: 'SBTHX_ZHONG_1', mul: 'MT_HE_ZHONG_1' },
  z2: { sub: 'SBTHX_ZHONG_2', mul: 'MT_HE_ZHONG_2' },
  z3: { sub: 'SBTHX_ZHONG_3', mul: 'MT_HE_ZHONG_3' },
  z4: { sub: 'SBTHX_ZHONG_4', mul: 'MT_HE_ZHONG_4' },
  z5: { sub: 'SBTHX_ZHONG_5', mul: 'MT_HE_ZHONG_5' },
  z6: { sub: 'SBTHX_ZHONG_6', mul: 'MT_HE_ZHONG_6' },
  z7: { sub: 'SBTHX_ZHONG_7', mul: 'MT_HE_ZHONG_7' },
  z8: { sub: 'SBTHX_ZHONG_8', mul: 'MT_HE_ZHONG_8' },
  z9: { sub: 'SBTHX_ZHONG_9', mul: 'MT_HE_ZHONG_9' },
  z10: { sub: 'SBTHX_ZHONG_10', mul: 'MT_HE_ZHONG_10' },
  bz2: { sub: 'SBTHX_BU_ZHONG_2', mul: 'MT_HE_BU_ZHONG_2' },
  bz3: { sub: 'SBTHX_BU_ZHONG_3', mul: 'MT_HE_BU_ZHONG_3' },
  bz4: { sub: 'SBTHX_BU_ZHONG_4', mul: 'MT_HE_BU_ZHONG_4' },
  bz5: { sub: 'SBTHX_BU_ZHONG_5', mul: 'MT_HE_BU_ZHONG_5' },
  bz6: { sub: 'SBTHX_BU_ZHONG_6', mul: 'MT_HE_BU_ZHONG_6' },
  bz7: { sub: 'SBTHX_BU_ZHONG_7', mul: 'MT_HE_BU_ZHONG_7' },
  bz8: { sub: 'SBTHX_BU_ZHONG_8', mul: 'MT_HE_BU_ZHONG_8' },
  bz9: { sub: 'SBTHX_BU_ZHONG_9', mul: 'MT_HE_BU_ZHONG_9' },
  bz10: { sub: 'SBTHX_BU_ZHONG_10', mul: 'MT_HE_BU_ZHONG_10' },
};

// 生肖连 子码对应关系 key: 中、不中首字母 + 选项条数
export const subSXBetTypeMap = {
  z2: { sub: 'SBTSXL_ZHONG_2', mul: 'MT_SXL_ZHONG_2' },
  z3: { sub: 'SBTSXL_ZHONG_3', mul: 'MT_SXL_ZHONG_3' },
  z4: { sub: 'SBTSXL_ZHONG_4', mul: 'MT_SXL_ZHONG_4' },
  z5: { sub: 'SBTSXL_ZHONG_5', mul: 'MT_SXL_ZHONG_5' },
  zb2: { sub: 'SBTSXL_ZHONG_2_BEN', mul: 'MT_SXL_ZHONG_2_BEN' },
  zb3: { sub: 'SBTSXL_ZHONG_3_BEN', mul: 'MT_SXL_ZHONG_3_BEN' },
  zb4: { sub: 'SBTSXL_ZHONG_4_BEN', mul: 'MT_SXL_ZHONG_4_BEN' },
  zb5: { sub: 'SBTSXL_ZHONG_5_BEN', mul: 'MT_SXL_ZHONG_5_BEN' },
  bz2: { sub: 'SBTSXL_BU_ZHONG_2', mul: 'MT_SXL_BU_ZHONG_2' },
  bz3: { sub: 'SBTSXL_BU_ZHONG_3', mul: 'MT_SXL_BU_ZHONG_3' },
  bz4: { sub: 'SBTSXL_BU_ZHONG_4', mul: 'MT_SXL_BU_ZHONG_4' },
  bz5: { sub: 'SBTSXL_BU_ZHONG_5', mul: 'MT_SXL_BU_ZHONG_5' },
  bzb2: { sub: 'SBTSXL_BU_ZHONG_2_BEN', mul: 'MT_SXL_BU_ZHONG_2_BEN' },
  bzb3: { sub: 'SBTSXL_BU_ZHONG_3_BEN', mul: 'MT_SXL_BU_ZHONG_3_BEN' },
  bzb4: { sub: 'SBTSXL_BU_ZHONG_4_BEN', mul: 'MT_SXL_BU_ZHONG_4_BEN' },
  bzb5: { sub: 'SBTSXL_BU_ZHONG_5_BEN', mul: 'MT_SXL_BU_ZHONG_5_BEN' },
};

// 展示赔率
export const getMul = ({ z, l, t }) => {
  const key = `${z}${curyearsx === t ? 'b' : ''}${l}`;
  return {
    mutil: subSXBetTypeMap[key]?.mul,
    subMainType: subSXBetTypeMap[key]?.sub,
  };
};

// 生肖连子码对应关系
export const subTypeCode = [
  {
    t: 'XIAO_LIAN_2',
    key: '2',
  },
  {
    t: 'XIAO_LIAN_3',
    key: '3',
  },
  {
    t: 'XIAO_LIAN_4',
    key: '4',
  },
  {
    t: 'XIAO_LIAN_5',
    key: '5',
  },
];

// 尾数连 子码对应关系 key: 中、不中首字母 + 选项条数
export const subWSLBetTypeMap = {
  z2: { sub: 'SBTWSL_ZHONG_2', mul: 'MT_WSL_ZHONG_2' },
  z3: { sub: 'SBTWSL_ZHONG_3', mul: 'MT_WSL_ZHONG_3' },
  z4: { sub: 'SBTWSL_ZHONG_4', mul: 'MT_WSL_ZHONG_4' },
  zb2: { sub: 'SBTWSL_ZHONG_2_0', mul: 'MT_WSL_ZHONG_2_0' },
  zb3: { sub: 'SBTWSL_ZHONG_3_0', mul: 'MT_WSL_ZHONG_3_0' },
  zb4: { sub: 'SBTWSL_ZHONG_4_0', mul: 'MT_WSL_ZHONG_4_0' },
  bz2: { sub: 'SBTWSL_BU_ZHONG_2', mul: 'MT_WSL_BU_ZHONG_2' },
  bz3: { sub: 'SBTWSL_BU_ZHONG_3', mul: 'MT_WSL_BU_ZHONG_3' },
  bz4: { sub: 'SBTWSL_BU_ZHONG_4', mul: 'MT_WSL_BU_ZHONG_4' },
  bzb2: { sub: 'SBTWSL_BU_ZHONG_2_0', mul: 'MT_WSL_BU_ZHONG_2_0' },
  bzb3: { sub: 'SBTWSL_BU_ZHONG_3_0', mul: 'MT_WSL_BU_ZHONG_3_0' },
  bzb4: { sub: 'SBTWSL_BU_ZHONG_4_0', mul: 'MT_WSL_BU_ZHONG_4_0' },
};

// 展示赔率
export const getWSLMul = ({ z, l, t }) => {
  const key = `${z}${+t === 0 ? 'b' : ''}${l}`;
  return {
    mutil: subWSLBetTypeMap[key]?.mul,
    subMainType: subWSLBetTypeMap[key]?.sub,
  };
};

// 尾数连子码对应关系
export const subWxTypeCode = [
  {
    t: 'WEI_LIAN_2',
    key: '2',
  },
  {
    t: 'WEI_LIAN_3',
    key: '3',
  },
  {
    t: 'WEI_LIAN_4',
    key: '4',
  },
];
