import { CMD_3501 } from '@/engine/game/pc/3501/CMD_3501';
import styels from '../index.module.scss';


// 特码tab标题及内容
export const tabListFirst = [
  {
    title: '总和',
    key: '1',
    listKey: 'sumArr',
  },
  {
    title: '分布',
    key: '2',
    listKey: 'partArr',
  },
];

export const tabListSecond = [
  {
    title: '连码',
    key: '1',
    listKey: 'conArr',
  },
];

// 3501 content 展示常量
export const betNumberList = [
  {
    title: '总和',
    paneKey: '1',
    list: [
      {
        text: '大',
        mutil: 'MT_H_DA',
        tMutil: '',
        key: '总和-大',
        topType: 'none',
        mainType: 'BTM_HE',
        subMainType: 'SBTH_DA',
        subTypeName: CMD_3501.emBetSubTypeNames[0],
        cls: 'm-r-20',
        child: [],
      },
      {
        text: '小',
        mutil: 'MT_H_XIAO',
        tMutil: '',
        key: '总和-小',
        mainType: 'BTM_HE',
        subMainType: 'SBTH_XIAO',
        topType: 'none',
        subTypeName: CMD_3501.emBetSubTypeNames[0],
        cls: 'm-r-20',
        child: [],
      },
      {
        text: '单',
        mutil: 'MT_H_DAN',
        tMutil: '',
        key: '总和-单',
        mainType: 'BTM_HE',
        subMainType: 'SBTH_DAN',
        topType: 'none',
        subTypeName: CMD_3501.emBetSubTypeNames[0],
        cls: 'm-r-20',
        child: [],
      },
      {
        text: '双',
        mutil: 'MT_H_SHUANG',
        tMutil: '',
        key: '总和-双',
        mainType: 'BTM_HE',
        subMainType: 'SBTH_SHUANG',
        topType: 'none',
        subTypeName: CMD_3501.emBetSubTypeNames[0],
        cls: 'm-r-20',
        child: [],
      },
      {
        text: '大单',
        mutil: 'MT_H_DA_DAN',
        key: '总和-大单',
        mainType: 'BTM_HE',
        subMainType: 'SBTH_DA_DAN',
        topType: 'none',
        subTypeName: CMD_3501.emBetSubTypeNames[0],
        cls: 'm-r-20',
        child: [],
      },
      {
        text: '小单',
        mutil: 'MT_H_XIAO_DAN',
        tMutil: '',
        key: '总和-小单',
        mainType: 'BTM_HE',
        subMainType: 'SBTH_XIAO_DAN',
        topType: 'none',
        subTypeName: CMD_3501.emBetSubTypeNames[0],
        cls: 'm-r-20',
        child: [],
      },
      {
        text: '大双',
        mutil: 'MT_H_DA_SHUANG',
        tMutil: '',
        key: '总和-大双',
        mainType: 'BTM_HE',
        subMainType: 'SBTH_DA_SHUANG',
        topType: 'none',
        subTypeName: CMD_3501.emBetSubTypeNames[0],
        cls: 'm-r-20',
        child: [],
      },
      {
        text: '小双',
        mutil: 'MT_H_XIAO_SHUANG',
        key: '总和-小双',
        mainType: 'BTM_HE',
        subMainType: 'SBTH_XIAO_SHUANG',
        topType: 'none',
        subTypeName: CMD_3501.emBetSubTypeNames[0],
        cls: 'm-r-20',
        child: [],
      },
      {
        text: '金',
        mutil: 'MT_H_JIN',
        key: '总和-金',
        mainType: 'BTM_HE',
        subMainType: 'SBTH_JIN',
        topType: 'none',
        subTypeName: CMD_3501.emBetSubTypeNames[0],
        cls: 'm-r-20',
        child: [],
      },
      {
        text: '木',
        mutil: 'MT_H_MU',
        key: '总和-木',
        mainType: 'BTM_HE',
        subMainType: 'SBTH_MU',
        topType: 'none',
        subTypeName: CMD_3501.emBetSubTypeNames[0],
        cls: 'm-r-20',
        child: [],
      },
      {
        text: '水',
        mutil: 'MT_H_SHUI',
        key: '总和-水',
        mainType: 'BTM_HE',
        subMainType: 'SBTH_SHUI',
        topType: 'none',
        subTypeName: CMD_3501.emBetSubTypeNames[0],
        cls: 'm-r-20',
        child: [],
      },
      {
        text: '火',
        mutil: 'MT_H_HUO',
        key: '总和-火',
        mainType: 'BTM_HE',
        subMainType: 'SBTH_HUO',
        topType: 'none',
        subTypeName: CMD_3501.emBetSubTypeNames[0],
        cls: 'm-r-20',
        child: [],
      },
      {
        text: '土',
        mutil: 'MT_H_TU',
        key: '总和-土',
        mainType: 'BTM_HE',
        subMainType: 'SBTH_TU',
        topType: 'none',
        subTypeName: CMD_3501.emBetSubTypeNames[0],
        cls: 'm-r-20',
        child: [],
      },
    ]
  },
  {
    title: '分布',
    paneKey: '2',
    list: [
      {
        text: '奇',
        mutil: 'MT_F_JI',
        tMutil: '',
        key: '分布-奇',
        topType: 'none',
        mainType: 'BTM_FENBU',
        subMainType: 'SBTF_JI',
        subTypeName: CMD_3501.emBetSubTypeNames[1],
        cls: 'm-r-20',
        child: [],
      },
      {
        text: '和',
        mutil: 'MT_F_HE',
        tMutil: '',
        key: '分布-和',
        topType: 'none',
        mainType: 'BTM_FENBU',
        subMainType: 'SBTF_HE',
        subTypeName: CMD_3501.emBetSubTypeNames[1],
        cls: 'm-r-20',
        child: [],
      },
      {
        text: '偶',
        mutil: 'MT_F_OU',
        tMutil: '',
        key: '分布-偶',
        topType: 'none',
        mainType: 'BTM_FENBU',
        subMainType: 'SBTF_OU',
        subTypeName: CMD_3501.emBetSubTypeNames[1],
        cls: 'm-r-20',
        child: [],
      },
      {
        text: '上',
        mutil: 'MT_F_SHANG',
        tMutil: '',
        key: '分布-上',
        topType: 'none',
        mainType: 'BTM_FENBU',
        subMainType: 'SBTF_SHANG',
        subTypeName: CMD_3501.emBetSubTypeNames[1],
        cls: 'm-r-20',
        child: [],
      },
      {
        text: '中',
        mutil: 'MT_F_ZHONG',
        tMutil: '',
        key: '分布-中',
        topType: 'none',
        mainType: 'BTM_FENBU',
        subMainType: 'SBTF_ZHONG',
        subTypeName: CMD_3501.emBetSubTypeNames[1],
        cls: 'm-r-20',
        child: [],
      },
      {
        text: '下',
        mutil: 'MT_F_XIA',
        tMutil: '',
        key: '分布-下',
        topType: 'none',
        mainType: 'BTM_FENBU',
        subMainType: 'SBTF_XIA',
        subTypeName: CMD_3501.emBetSubTypeNames[1],
        cls: 'm-r-20',
        child: [],
      },

    ]
  },
  {
    title: '任选',
    paneKey: '3',
    list: [
      {
        text: '任选五',
        mutil: 'MT_R_XUAN5',
        tMutil: [],
        key: '任选-任选五',
        topType: 'none',
        mainType: 'BTM_RENXUAN',
        subMainType: 'SBTR_XUAN5',
        subTypeName: CMD_3501.emBetSubTypeNames[2],
        len: 5,
        cls: styels['t-large'],
        child: [
          {
            text: '五中五',
            mutil: '',
            tMutil: 'MT_R_XUAN5_5',
            key: '任选-五中五',
            topType: 'none',
            mainType: 'BTM_RENXUAN',
            subMainType: 'SBTR_XUAN5',
            subTypeName: CMD_3501.emBetSubTypeNames[2],
            cls: styels['t-large'],
          },
          {
            text: '五中四',
            mutil: '',
            tMutil: 'MT_R_XUAN5_4',
            key: '任选-五中四',
            topType: 'none',
            mainType: 'BTM_RENXUAN',
            subMainType: 'SBTR_XUAN5',
            subTypeName: CMD_3501.emBetSubTypeNames[2],
            cls: styels['t-large'],
          },
          {
            text: '五中三',
            mutil: 'MT_R_XUAN5',
            tMutil: '',
            key: '任选-五中三',
            topType: 'none',
            mainType: 'BTM_RENXUAN',
            subMainType: 'SBTR_XUAN5',
            subTypeName: CMD_3501.emBetSubTypeNames[2],
            cls: styels['t-large'],
          }
        ]
      },
      {
        text: '任选四',
        mutil: 'MT_R_XUAN4',
        tMutil: '',
        key: '任选-任选四',
        topType: 'none',
        mainType: 'BTM_RENXUAN',
        subMainType: 'SBTR_XUAN4',
        subTypeName: CMD_3501.emBetSubTypeNames[2],
        len: 4,
        cls: styels['t-large'],
        child: [
          {
            text: '四中四',
            mutil: '',
            tMutil: 'MT_R_XUAN4_4',
            key: '任选-四中四',
            topType: 'none',
            mainType: 'BTM_RENXUAN',
            subMainType: 'SBTR_XUAN4',
            subTypeName: CMD_3501.emBetSubTypeNames[2],
            cls: styels['t-large'],
          },
          {
            text: '四中三',
            mutil: '',
            tMutil: 'MT_R_XUAN4_3',
            key: '任选-四中三',
            topType: 'none',
            mainType: 'BTM_RENXUAN',
            subMainType: 'SBTR_XUAN4',
            subTypeName: CMD_3501.emBetSubTypeNames[2],
            cls: styels['t-large'],
          },
          {
            text: '四中二',
            mutil: 'MT_R_XUAN4',
            tMutil: '',
            key: '任选-四中二',
            topType: 'none',
            mainType: 'BTM_RENXUAN',
            subMainType: 'SBTR_XUAN4',
            subTypeName: CMD_3501.emBetSubTypeNames[2],
            cls: styels['t-large'],
          },
          
        ]
      },
      {
        text: '任选三',
        mutil: 'MT_R_XUAN3',
        tMutil: '',
        key: '任选-任选三',
        topType: 'none',
        mainType: 'BTM_RENXUAN',
        subMainType: 'SBTR_XUAN3',
        subTypeName: CMD_3501.emBetSubTypeNames[2],
        len: 3,
        cls: styels['t-large'],
        child: [
          {
            text: '三中三',
            mutil: '',
            tMutil: 'MT_R_XUAN3_3',
            key: '任选-三中三',
            topType: 'none',
            mainType: 'BTM_RENXUAN',
            subMainType: 'SBTR_XUAN3',
            subTypeName: CMD_3501.emBetSubTypeNames[2],
            cls: styels['t-large'],
          },
          {
            text: '三中二',
            mutil: 'MT_R_XUAN3',
            tMutil: '',
            key: '任选-三中二',
            topType: 'none',
            mainType: 'BTM_RENXUAN',
            subMainType: 'SBTR_XUAN3',
            subTypeName: CMD_3501.emBetSubTypeNames[2],
            cls: styels['t-large'],
          },
        ]
      },
      {
        text: '任选二',
        mutil: 'MT_R_XUAN2',
        tMutil: '',
        key: '任选-任选二',
        topType: 'none',
        mainType: 'BTM_RENXUAN',
        subMainType: 'SBTR_XUAN2',
        len: 2,
        cls: styels['t-large'],
        child: [
          {
            text: '二中二',
            mutil: 'MT_R_XUAN2',
            tMutil: '',
            key: '任选-二中二',
            topType: 'none',
            mainType: 'BTM_RENXUAN',
            subMainType: 'SBTR_XUAN2',
            subTypeName: CMD_3501.emBetSubTypeNames[2],
            cls: styels['t-large'],
          },
        ]
      },
      {
        text: '任选一',
        mutil: 'MT_R_XUAN1',
        tMutil: '',
        key: '任选-任选一',
        topType: 'none',
        mainType: 'BTM_RENXUAN',
        subMainType: 'SBTR_XUAN1',
        len: 1,
        cls: styels['t-large'],
        child: [
          {
            text: '一中一',
            mutil: 'MT_R_XUAN1',
            tMutil: '',
            key: '任选-一中一',
            topType: 'none',
            mainType: 'BTM_RENXUAN',
            subMainType: 'SBTR_XUAN1',
            subTypeName: CMD_3501.emBetSubTypeNames[2],
            cls: styels['t-large'],
          },
        ]
      },
    ]
  }
];
