import styels from './index.module.scss';
import { CMD_2801 } from '@/engine/game/28/2801/CMD_2801';

export const betNumberList = [
  {
    title: 'TE',
    paneKey: '1',
    list: [
      {
        text: 'DA',
        mutil: 'MT_T_DA',
        tMutil: 'MT_T_DA_S',
        key: '',
        topType: 'none',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_DA',
        cls: styels['t-large'],
      },
      {
        text: 'DAN',
        mutil: 'MT_T_DAN',
        tMutil: 'MT_T_DAN_S',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_DAN',
        topType: 'none',
        cls: styels['t-large'],
      },
      {
        text: 'DA_DAN',
        mutil: 'MT_T_DA_DAN',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_DA_DAN',
        topType: 'none',
        cls: styels['t-large'],
      },
      {
        text: 'XIAO_DAN',
        mutil: 'MT_T_XIAO_DAN',
        tMutil: 'MT_T_XIAO_DAN_S',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_XIAO_DAN',
        topType: 'none',
        cls: styels['t-large'],
      },
      {
        text: 'JIDA',
        mutil: 'MT_T_JIDA',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_JIDA',
        topType: 'none',
        cls: styels['t-large'],
      },
      {
        text: 'XIAO',
        mutil: 'MT_T_XIAO',
        tMutil: 'MT_T_XIAO_S',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_XIAO',
        topType: 'none',
        cls: styels['t-large'],
      },
      {
        text: 'SHUANG',
        mutil: 'MT_T_SHUANG',
        tMutil: 'MT_T_SHUANG_S',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_SHUANG',
        topType: 'none',
        cls: styels['t-large'],
      },
      {
        text: 'DA_SHUANG',
        mutil: 'MT_T_DA_SHUANG',
        tMutil: 'MT_T_DA_SHUANG_S',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_DA_SHUANG',
        topType: 'none',
        cls: styels['t-large'],
      },
      {
        text: 'XIAO_SHUANG',
        mutil: 'MT_T_XIAO_SHUANG',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_XIAO_SHUANG',
        topType: 'none',
        cls: styels['t-large'],
      },
      {
        text: 'JIXIAO',
        mutil: 'MT_T_JIXIAO',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_JIXIAO',
        topType: 'none',
        cls: styels['t-large'],
      },
      {
        text: 'HONG',
        mutil: 'MT_T_HONG',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_HONG',
        topType: 'none',
        cls: styels['t-nomal'],
      },
      {
        text: 'LAN',
        mutil: 'MT_T_LAN',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_LAN',
        topType: 'none',
        cls: styels['t-nomal'],
      },
      {
        text: 'LV',
        mutil: 'MT_T_LV',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_LV',
        topType: 'none',
        cls: styels['t-nomal'],
      },
      {
        text: 'SHUNZI',
        mutil: 'MT_T_SHUNZI',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_SHUNZI',
        topType: 'none',
        cls: styels['t-nomal'],
      },
      {
        text: 'BAOZI',
        mutil: 'MT_T_BAOZI',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_BAOZI',
        topType: 'none',
        cls: styels['t-nomal'],
      },
      {
        text: 'DUIZI',
        mutil: 'MT_T_DUIZI',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_DUIZI',
        topType: 'none',
        cls: styels['t-nomal'],
      },
      {
        text: '00',
        mutil: 'MT_T_0',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_NUM',
        cls: styels['t-nomal'],
      },
      {
        text: '01',
        mutil: 'MT_T_1',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_NUM',
        cls: styels['t-nomal'],
      },
      {
        text: '02',
        mutil: 'MT_T_2',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_NUM',
        cls: styels['t-nomal'],
      },
      {
        text: '03',
        mutil: 'MT_T_3',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_NUM',
        cls: styels['t-nomal'],
      },
      {
        text: '04',
        mutil: 'MT_T_4',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_NUM',
        cls: styels['t-nomal'],
      },
      {
        text: '05',
        mutil: 'MT_T_5',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_NUM',
        cls: styels['t-nomal'],
      },
      {
        text: '06',
        mutil: 'MT_T_6',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_NUM',
        cls: styels['t-nomal'],
      },
      {
        text: '07',
        mutil: 'MT_T_7',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_NUM',
        cls: styels['t-nomal'],
      },
      {
        text: '08',
        mutil: 'MT_T_8',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_NUM',
        cls: styels['t-nomal'],
      },
      {
        text: '09',
        mutil: 'MT_T_9',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_NUM',
        cls: styels['t-nomal'],
      },
      {
        text: '10',
        mutil: 'MT_T_10',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_NUM',
        cls: styels['t-nomal'],
      },
      {
        text: '11',
        mutil: 'MT_T_11',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_NUM',
        cls: styels['t-nomal'],
      },
      {
        text: '12',
        mutil: 'MT_T_12',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_NUM',
        cls: styels['t-nomal'],
      },
      {
        text: '13',
        mutil: 'MT_T_13',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_NUM',
        cls: styels['t-nomal'],
      },
      {
        text: '14',
        mutil: 'MT_T_13',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_NUM',
        cls: styels['t-nomal'],
      },
      {
        text: '15',
        mutil: 'MT_T_12',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_NUM',
        cls: styels['t-nomal'],
      },
      {
        text: '16',
        mutil: 'MT_T_11',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_NUM',
        cls: styels['t-nomal'],
      },
      {
        text: '17',
        mutil: 'MT_T_10',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_NUM',
        cls: styels['t-nomal'],
      },
      {
        text: '18',
        mutil: 'MT_T_9',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_NUM',
        cls: styels['t-nomal'],
      },
      {
        text: '19',
        mutil: 'MT_T_8',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_NUM',
        cls: styels['t-nomal'],
      },
      {
        text: '20',
        mutil: 'MT_T_7',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_NUM',
        cls: styels['t-nomal'],
      },
      {
        text: '21',
        mutil: 'MT_T_6',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_NUM',
        cls: styels['t-nomal'],
      },
      {
        text: '22',
        mutil: 'MT_T_5',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_NUM',
        cls: styels['t-nomal'],
      },
      {
        text: '23',
        mutil: 'MT_T_4',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_NUM',
        cls: styels['t-nomal'],
      },
      {
        text: '24',
        mutil: 'MT_T_3',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_NUM',
        cls: styels['t-nomal'],
      },
      {
        text: '25',
        mutil: 'MT_T_2',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_NUM',
        cls: styels['t-nomal'],
      },
      {
        text: '26',
        mutil: 'MT_T_1',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_NUM',
        cls: styels['t-nomal'],
      },
      {
        text: '27',
        mutil: 'MT_T_0',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_NUM',
        cls: styels['t-nomal'],
      },
    ],
  },
  {
    title: 'DING_1',
    paneKey: '2',
    list: [
      {
        text: '0',
        mutil: 'MT_D1_DIAN',
        key: '',
        mainType: 'BTM_DING_1',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_NUM',
        cls: styels['t-large'],
      },
      {
        text: '1',
        mutil: 'MT_D1_DIAN',
        key: '',
        mainType: 'BTM_DING_1',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_NUM',
        cls: styels['t-large'],
      },
      {
        text: '2',
        mutil: 'MT_D1_DIAN',
        key: '',
        mainType: 'BTM_DING_1',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_NUM',
        cls: styels['t-large'],
      },
      {
        text: '3',
        mutil: 'MT_D1_DIAN',
        key: '',
        mainType: 'BTM_DING_1',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_NUM',
        cls: styels['t-large'],
      },
      {
        text: '4',
        mutil: 'MT_D1_DIAN',
        key: '',
        mainType: 'BTM_DING_1',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_NUM',
        cls: styels['t-large'],
      },
      {
        text: '5',
        mutil: 'MT_D1_DIAN',
        key: '',
        mainType: 'BTM_DING_1',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_NUM',
        cls: styels['t-large'],
      },
      {
        text: '6',
        mutil: 'MT_D1_DIAN',
        key: '',
        mainType: 'BTM_DING_1',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_NUM',
        cls: styels['t-large'],
      },
      {
        text: '7',
        mutil: 'MT_D1_DIAN',
        key: '',
        mainType: 'BTM_DING_1',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_NUM',
        cls: styels['t-large'],
      },
      {
        text: '8',
        mutil: 'MT_D1_DIAN',
        key: '',
        mainType: 'BTM_DING_1',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_NUM',
        cls: styels['t-large'],
      },
      {
        text: '9',
        mutil: 'MT_D1_DIAN',
        key: '',
        mainType: 'BTM_DING_1',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_NUM',
        cls: styels['t-large'],
      },
      {
        text: 'DA',
        topType: 'none',
        cls: styels['t-large'],
        mutil: 'MT_D1_DA',
        key: '',
        mainType: 'BTM_DING_1',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_DA',
      },
      {
        text: 'XIAO',
        topType: 'none',
        cls: styels['t-large'],
        mutil: 'MT_D1_XIAO',
        key: '',
        mainType: 'BTM_DING_1',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_XIAO',
      },
      {
        text: 'DAN',
        topType: 'none',
        cls: styels['t-large'],
        mutil: 'MT_D1_DAN',
        key: '',
        mainType: 'BTM_DING_1',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_DAN',
      },
      {
        text: 'SHUANG',
        topType: 'none',
        cls: styels['t-large'],
        mutil: 'MT_D1_SHUANG',
        key: '',
        mainType: 'BTM_DING_1',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_SHUANG',
      },
      {
        text: 'LONG',
        mutil: 'MT_T_LONG',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_LONG',
        topType: 'none',
        cls: styels['t-large'],
      },
    ],
  },
  {
    title: 'DING_2',
    paneKey: '3',
    list: [
      {
        text: '0',
        mutil: 'MT_D2_DIAN',
        key: '',
        mainType: 'BTM_DING_2',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_NUM',
        cls: styels['t-large'],
      },
      {
        text: '1',
        mutil: 'MT_D2_DIAN',
        key: '',
        mainType: 'BTM_DING_2',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_NUM',
        cls: styels['t-large'],
      },
      {
        text: '2',
        mutil: 'MT_D2_DIAN',
        key: '',
        mainType: 'BTM_DING_2',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_NUM',
        cls: styels['t-large'],
      },
      {
        text: '3',
        mutil: 'MT_D2_DIAN',
        key: '',
        mainType: 'BTM_DING_2',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_NUM',
        cls: styels['t-large'],
      },
      {
        text: '4',
        mutil: 'MT_D2_DIAN',
        key: '',
        mainType: 'BTM_DING_2',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_NUM',
        cls: styels['t-large'],
      },
      {
        text: '5',
        mutil: 'MT_D2_DIAN',
        key: '',
        mainType: 'BTM_DING_2',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_NUM',
        cls: styels['t-large'],
      },
      {
        text: '6',
        mutil: 'MT_D2_DIAN',
        key: '',
        mainType: 'BTM_DING_2',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_NUM',
        cls: styels['t-large'],
      },
      {
        text: '7',
        mutil: 'MT_D2_DIAN',
        key: '',
        mainType: 'BTM_DING_2',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_NUM',
        cls: styels['t-large'],
      },
      {
        text: '8',
        mutil: 'MT_D2_DIAN',
        key: '',
        mainType: 'BTM_DING_2',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_NUM',
        cls: styels['t-large'],
      },
      {
        text: '9',
        mutil: 'MT_D2_DIAN',
        key: '',
        mainType: 'BTM_DING_2',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_NUM',
        cls: styels['t-large'],
      },
      {
        text: 'DA',
        topType: 'none',
        cls: styels['t-large'],
        mutil: 'MT_D2_DA',
        key: '',
        mainType: 'BTM_DING_2',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_DA',
      },
      {
        text: 'XIAO',
        topType: 'none',
        cls: styels['t-large'],
        mutil: 'MT_D2_XIAO',
        key: '',
        mainType: 'BTM_DING_2',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_XIAO',
      },
      {
        text: 'DAN',
        topType: 'none',
        cls: styels['t-large'],
        mutil: 'MT_D2_DAN',
        key: '',
        mainType: 'BTM_DING_2',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_DAN',
      },
      {
        text: 'SHUANG',
        topType: 'none',
        cls: styels['t-large'],
        mutil: 'MT_D2_SHUANG',
        key: '',
        mainType: 'BTM_DING_2',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_SHUANG',
      },
      {
        text: 'HU',
        mutil: 'MT_T_HU',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_HU',
        topType: 'none',
        cls: styels['t-large'],
      },
    ],
  },
  {
    title: 'DING_3',
    paneKey: '4',
    list: [
      {
        text: '0',
        mutil: 'MT_D3_DIAN',
        key: '',
        mainType: 'BTM_DING_3',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_NUM',
        cls: styels['t-large'],
      },
      {
        text: '1',
        mutil: 'MT_D3_DIAN',
        key: '',
        mainType: 'BTM_DING_3',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_NUM',
        cls: styels['t-large'],
      },
      {
        text: '2',
        mutil: 'MT_D3_DIAN',
        key: '',
        mainType: 'BTM_DING_3',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_NUM',
        cls: styels['t-large'],
      },
      {
        text: '3',
        mutil: 'MT_D3_DIAN',
        key: '',
        mainType: 'BTM_DING_3',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_NUM',
        cls: styels['t-large'],
      },
      {
        text: '4',
        mutil: 'MT_D3_DIAN',
        key: '',
        mainType: 'BTM_DING_3',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_NUM',
        cls: styels['t-large'],
      },
      {
        text: '5',
        mutil: 'MT_D3_DIAN',
        key: '',
        mainType: 'BTM_DING_3',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_NUM',
        cls: styels['t-large'],
      },
      {
        text: '6',
        mutil: 'MT_D3_DIAN',
        key: '',
        mainType: 'BTM_DING_3',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_NUM',
        cls: styels['t-large'],
      },
      {
        text: '7',
        mutil: 'MT_D3_DIAN',
        key: '',
        mainType: 'BTM_DING_3',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_NUM',
        cls: styels['t-large'],
      },
      {
        text: '8',
        mutil: 'MT_D3_DIAN',
        key: '',
        mainType: 'BTM_DING_3',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_NUM',
        cls: styels['t-large'],
      },
      {
        text: '9',
        mutil: 'MT_D3_DIAN',
        key: '',
        mainType: 'BTM_DING_3',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_NUM',
        cls: styels['t-large'],
      },
      {
        text: 'DA',
        topType: 'none',
        cls: styels['t-large'],
        mutil: 'MT_D3_DA',
        key: '',
        mainType: 'BTM_DING_3',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_DA',
      },
      {
        text: 'XIAO',
        topType: 'none',
        cls: styels['t-large'],
        mutil: 'MT_D3_XIAO',
        key: '',
        mainType: 'BTM_DING_3',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_XIAO',
      },
      {
        text: 'DAN',
        topType: 'none',
        cls: styels['t-large'],
        mutil: 'MT_D3_DAN',
        key: '',
        mainType: 'BTM_DING_3',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_DAN',
      },
      {
        text: 'SHUANG',
        topType: 'none',
        cls: styels['t-large'],
        mutil: 'MT_D3_SHUANG',
        key: '',
        mainType: 'BTM_DING_3',
        subTypeName: CMD_2801.emBetSubTypeNames[1],
        subMainType: 'SBTD_SHUANG',
      },
      {
        text: 'HE',
        mutil: 'MT_T_HE',
        key: '',
        mainType: 'BTM_TE',
        subTypeName: CMD_2801.emBetSubTypeNames[0],
        subMainType: 'SBTT_HE',
        topType: 'none',
        cls: styels['t-large'],
      },
    ],
  },
];
